// Polis sprite manifest — the typed index of every real-art sprite the renderer
// may use, keyed by SEMANTIC key, decoupled from atlas layout.
//
// KEY GRAMMAR (stable API for the whole sprite round; consumers never touch
// frame names):
//   bld:{purpose}:{level}:v{n}   whole-building sprite variant (A5b)
//   tex:{surface}                seamless fill texture (grass/cobble/plaster/...)
//   prop:{kind}:v{n}             scatter prop (olive/rock/stall/...)
//   field:{kind}                 farmland parcel texture per fields.ts kind
//   fx:{effect}:f{n}             flipbook effect frame (fire/smoke, A7)
//
// GENERATION: this file is emitted by tools/polis-art/manifest.py (phase A2)
// from docs/polis-art-ledger.json + the packed atlases in public/polis/atlas/.
// GENERATED by tools/polis-art/manifest.py — do NOT hand-edit; re-run the pipeline instead. An EMPTY manifest is the shipped state of record until
// assets land — loadPolisSprites returns null and every draw path stays on the
// procedural kit.

/**
 * Per-sprite metadata carried alongside the atlas frame reference. Deliberately
 * deep-readonly: entries are shared by reference between the manifest and every
 * SpriteBank, so a writable field here would let one consumer silently corrupt
 * the anchor/footprint of every building using the same key.
 */
export interface SpriteEntryMeta {
  /** Frame name inside the owning atlas spritesheet. */
  readonly frame: string;
  /** Id of the atlas page (key into SpriteManifest.atlases) holding the frame. */
  readonly atlas: string;
  /** Building footprint in tiles [W, D] — building sprites only. */
  readonly foot?: readonly [number, number];
  /**
   * Anchor in normalized texture coords. Default [0.5, 1]: bottom-center, so a
   * sprite placed at the footprint's front-corner iso point sits on the ground
   * like the kit containers do.
   */
  readonly anchor?: readonly [number, number];
  /**
   * True when the source art bakes its own ground shadow — the renderer must
   * then skip our contact-shadow sprite for this variant or shadows double up.
   */
  readonly hasBakedShadow?: boolean;
}

export interface SpriteManifest {
  version: 1;
  /**
   * Atlas pages: page id -> spritesheet JSON url (app-root relative, served
   * from public/polis/atlas/, CSP 'self').
   */
  atlases: Record<string, string>;
  /** Standalone repeatable textures: key -> PNG url (pow2, wrap-repeat). */
  readonly singles?: Record<string, string>;
  /** Semantic key -> frame metadata. */
  entries: Record<string, SpriteEntryMeta>;
}

/** Shipped manifest. Empty until phase A2/A3 land the first packed atlases. */
export const SPRITE_MANIFEST: SpriteManifest = {
  version: 1,
  atlases: {
    "fx-0": "./atlas/fx-0.json",
    "prop-0": "./atlas/prop-0.json",
    "res-0": "./atlas/res-0.json",
  },
  singles: {
    "tex:ashlar": "./atlas/tex__ashlar.png",
    "tex:cobble": "./atlas/tex__cobble.png",
    "tex:dirt": "./atlas/tex__dirt.png",
    "tex:dirtolive": "./atlas/tex__dirtolive.png",
    "tex:grass": "./atlas/tex__grass.png",
    "tex:grassdark": "./atlas/tex__grassdark.png",
    "tex:grassdry": "./atlas/tex__grassdry.png",
    "tex:marble": "./atlas/tex__marble.png",
    "tex:plaster": "./atlas/tex__plaster.png",
    "tex:plasterwarm": "./atlas/tex__plasterwarm.png",
    "tex:rooftile": "./atlas/tex__rooftile.png",
    "tex:stonegrey": "./atlas/tex__stonegrey.png",
    "tex:thatch": "./atlas/tex__thatch.png",
    "tex:water": "./atlas/tex__water.png",
    "tex:waterdeep": "./atlas/tex__waterdeep.png",
    "tex:wood": "./atlas/tex__wood.png",
  },
  entries: {
    "fx:fire:f0": {
      frame: "fx:fire:f0",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "fx:fire:f1": {
      frame: "fx:fire:f1",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "fx:fire:f2": {
      frame: "fx:fire:f2",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "fx:fire:f3": {
      frame: "fx:fire:f3",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "fx:fire:f4": {
      frame: "fx:fire:f4",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "fx:fire:f5": {
      frame: "fx:fire:f5",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "fx:fire:f6": {
      frame: "fx:fire:f6",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "fx:fire:f7": {
      frame: "fx:fire:f7",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "fx:fire:f8": {
      frame: "fx:fire:f8",
      atlas: "fx-0",
      anchor: [0.5, 0.95],
    },
    "prop:cypress:v0": {
      frame: "prop:cypress:v0",
      atlas: "prop-0",
      foot: [1, 1],
    },
    "prop:cypress:v1": {
      frame: "prop:cypress:v1",
      atlas: "prop-0",
      foot: [1, 1],
    },
    "prop:cypress:v2": {
      frame: "prop:cypress:v2",
      atlas: "prop-0",
      foot: [1, 1],
    },
    "prop:rock:v0": {
      frame: "prop:rock:v0",
      atlas: "prop-0",
      hasBakedShadow: true,
    },
    "prop:rock:v1": {
      frame: "prop:rock:v1",
      atlas: "prop-0",
      hasBakedShadow: true,
    },
    "prop:rock:v2": {
      frame: "prop:rock:v2",
      atlas: "prop-0",
      hasBakedShadow: true,
    },
    "prop:rock:v3": {
      frame: "prop:rock:v3",
      atlas: "prop-0",
      hasBakedShadow: true,
    },
    "prop:rock:v4": {
      frame: "prop:rock:v4",
      atlas: "prop-0",
      hasBakedShadow: true,
    },
    "prop:tree:v0": {
      frame: "prop:tree:v0",
      atlas: "prop-0",
      foot: [1, 1],
    },
    "prop:tree:v1": {
      frame: "prop:tree:v1",
      atlas: "prop-0",
      foot: [1, 1],
    },
    "prop:tree:v2": {
      frame: "prop:tree:v2",
      atlas: "prop-0",
      foot: [1, 1],
    },
    "prop:tree:v3": {
      frame: "prop:tree:v3",
      atlas: "prop-0",
      foot: [1, 1],
    },
    "res:mine": {
      frame: "res:mine",
      atlas: "res-0",
      hasBakedShadow: true,
    },
    "res:quarry:v0": {
      frame: "res:quarry:v0",
      atlas: "res-0",
      hasBakedShadow: true,
    },
    "res:quarry:v1": {
      frame: "res:quarry:v1",
      atlas: "res-0",
      hasBakedShadow: true,
    },
  },
};
