// @vitest-environment happy-dom

import { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useAppStore } from "../../store/appStore";
import {
  ATTACHMENT_DELIVERY_NOTICE,
  ATTACHMENT_INPUT_ACCEPT,
  formatAttachmentSize,
} from "./designAttachments";
import { DesignSurface, type DesignDocument, type DesignHost } from "./DesignSurface";
import type { DesignGenerationOptions } from "./designHost";

const settingsMocks = vi.hoisted(() => ({
  load: vi.fn(),
  save: vi.fn(),
  loadProvider: vi.fn(),
  loadStoredProvider: vi.fn(),
  saveProvider: vi.fn(),
  loadWorkspace: vi.fn(),
  loadStoredWorkspace: vi.fn(),
  saveWorkspace: vi.fn(),
  loadOutput: vi.fn(),
  saveOutput: vi.fn(),
}));

const providerMocks = vi.hoisted(() => ({
  daemonStatus: vi.fn(),
  list: vi.fn(),
  projectsList: vi.fn(),
  workspacesList: vi.fn(),
}));

vi.mock("./designSettings", async () => {
  const actual = await vi.importActual<typeof import("./designSettings")>("./designSettings");
  return {
    ...actual,
    loadDesignSkillSelection: settingsMocks.load,
    saveDesignSkillSelection: settingsMocks.save,
    loadDesignProviderId: settingsMocks.loadProvider,
    loadStoredDesignProviderId: settingsMocks.loadStoredProvider,
    saveDesignProviderId: settingsMocks.saveProvider,
    loadDesignWorkspaceId: settingsMocks.loadWorkspace,
    loadStoredDesignWorkspaceId: settingsMocks.loadStoredWorkspace,
    saveDesignWorkspaceId: settingsMocks.saveWorkspace,
    loadDesignOutputMode: settingsMocks.loadOutput,
    saveDesignOutputMode: settingsMocks.saveOutput,
  };
});

vi.mock("./DesignHistoryList", () => ({
  DesignHistoryList: () => null,
}));

vi.mock("./designHistory", () => ({
  recordDesignHistoryEntry: vi.fn(async () => true),
}));

vi.mock("./designHistoryOpen", () => ({
  openDesignHistoryEntry: vi.fn(),
}));

vi.mock("../../lib/tauri", () => ({
  daemonStatus: providerMocks.daemonStatus,
  providersList: providerMocks.list,
  projectsList: providerMocks.projectsList,
  workspacesList: providerMocks.workspacesList,
  reasonFromCause: (cause: unknown) => (cause instanceof Error ? cause.message : String(cause)),
  createSessionStateChannel: vi.fn(),
  sessionCreate: vi.fn(),
  sessionsList: vi.fn(),
  sessionsUnwatch: vi.fn(),
  sessionsWatch: vi.fn(),
}));

(
  globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

const DOCUMENT: DesignDocument = {
  name: "Attachment test",
  path: "~/dev/design",
  contextPrefix: "Editing",
  draftPlaceholder: "Describe the change…",
  noContextPlaceholder: "Describe what to generate…",
  selectedLayerId: "",
  grounded: true,
  initialState: { zoom: 1, saved: true, draft: "", hiddenLayerIds: [] },
  layers: [],
  messages: [],
  workingMessage: { title: "Generating…", desc: "Asking the agent." },
};

const GENERATION_BASE = {
  sessionId: "session-attachments",
  peerSessionId: null,
  createdAtMs: 1_000,
  prompt: "host echo",
  title: "Generated result",
  desc: "Generated by the host.",
  sources: [],
  nodeIds: [],
};

function asciiBytes(text: string): number[] {
  return [...text].map((character) => character.charCodeAt(0));
}

/** One PNG chunk; the four trailing bytes stand in for a CRC this code never rebuilds. */
function pngChunk(type: string, data: readonly number[]): number[] {
  const length = data.length;
  return [
    (length >>> 24) & 0xff,
    (length >>> 16) & 0xff,
    (length >>> 8) & 0xff,
    length & 0xff,
    ...asciiBytes(type),
    ...data,
    0xde,
    0xad,
    0xbe,
    0xef,
  ];
}

// A whole, walkable PNG: `importDesignAttachments` now reads every raster's
// segments before carrying it, so a bare signature is no longer a valid stand-in.
const PNG_BYTES = Uint8Array.from([
  ...asciiBytes("\u0089PNG\r\n\u001a\n"),
  ...pngChunk("IHDR", [0, 0, 0, 1, 0, 0, 0, 1, 8, 6, 0, 0, 0]),
  ...pngChunk("IDAT", [0x78, 0x9c, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01]),
  ...pngChunk("IEND", []),
]);
const CLEAN_SVG = '<svg xmlns="http://www.w3.org/2000/svg"><rect width="4" height="4"/></svg>';

function imageFile(name: string, bytes: Uint8Array<ArrayBuffer>, type: string): File {
  return new File([bytes], name, { type });
}

function createHost(overrides: Partial<DesignHost> = {}): DesignHost {
  return {
    loadDocument: vi.fn(async () => DOCUMENT),
    saveDocument: vi.fn(async () => undefined),
    // Present by default: the composer only renders for a host that can generate,
    // and every entry below lives inside that composer.
    generate: vi.fn(async () => ({ ...GENERATION_BASE })),
    ...overrides,
  };
}

async function renderDesign(host: DesignHost): Promise<{
  container: HTMLDivElement;
  root: ReturnType<typeof createRoot>;
}> {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root = createRoot(container);
  await act(async () => {
    root.render(<DesignSurface host={host} />);
    await Promise.resolve();
    await Promise.resolve();
  });
  return { container, root };
}

function composer(container: HTMLDivElement): HTMLDivElement {
  const element = container.querySelector<HTMLDivElement>(".design-composer");
  if (element === null) throw new Error("Composer missing");
  return element;
}

function draftField(container: HTMLDivElement): HTMLTextAreaElement {
  const field = container.querySelector<HTMLTextAreaElement>(
    'textarea[aria-label="Describe a design change"]',
  );
  if (field === null) throw new Error("Design composer missing");
  return field;
}

/**
 * happy-dom's DataTransfer is a stub, so the payload is a plain object hung off the
 * event. React reads `dataTransfer` off the native event, which is exactly what the
 * component's handlers do too, so the path under test is the real one.
 */
async function dispatchTransferEvent(
  target: Element,
  type: "dragenter" | "dragover" | "dragleave" | "drop" | "paste",
  dataTransfer: unknown,
): Promise<Event> {
  const event = new Event(type, { bubbles: true, cancelable: true });
  Object.defineProperty(event, "dataTransfer", { value: dataTransfer });
  Object.defineProperty(event, "clipboardData", { value: dataTransfer });
  await act(async () => {
    target.dispatchEvent(event);
    await Promise.resolve();
    await Promise.resolve();
    await Promise.resolve();
  });
  return event;
}

function pillNames(container: HTMLDivElement): string[] {
  return Array.from(container.querySelectorAll(".design-attachment-name")).map(
    (element) => element.textContent ?? "",
  );
}

function feedback(container: HTMLDivElement): readonly string[] {
  return Array.from(container.querySelectorAll(".design-attachment-feedback p")).map(
    (element) => element.textContent ?? "",
  );
}

function notice(container: HTMLDivElement): HTMLElement | null {
  return container.querySelector<HTMLElement>(".design-attachment-notice");
}

async function fillDraft(container: HTMLDivElement, prompt: string): Promise<void> {
  const setValue = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set;
  if (setValue === undefined) throw new Error("textarea value setter did not exist");
  await act(async () => {
    setValue.call(draftField(container), prompt);
    draftField(container).dispatchEvent(new Event("input", { bubbles: true }));
  });
}

beforeEach(() => {
  useAppStore.setState({ plugins: null, installing: null, installError: null });
  settingsMocks.load.mockResolvedValue({ version: 1, mode: "all", enabledSlugs: [] });
  settingsMocks.loadProvider.mockResolvedValue(null);
  settingsMocks.loadStoredProvider.mockResolvedValue(null);
  settingsMocks.loadWorkspace.mockResolvedValue(null);
  settingsMocks.loadStoredWorkspace.mockResolvedValue(null);
  settingsMocks.loadOutput.mockResolvedValue("page");
  providerMocks.daemonStatus.mockResolvedValue({ capabilities: [] });
  providerMocks.list.mockResolvedValue({ providers: [], unreadableDirs: 0 });
  providerMocks.projectsList.mockResolvedValue([]);
  providerMocks.workspacesList.mockResolvedValue([]);
});

afterEach(() => {
  document.body.replaceChildren();
  vi.clearAllMocks();
});

describe("the picker is a keyboard-reachable control", () => {
  it("puts a real button in the composer's control strip", async () => {
    await renderDesign(createHost());

    const button = document.querySelector<HTMLButtonElement>(".design-attach-button");
    expect(button).not.toBeNull();
    expect(button?.getAttribute("aria-label")).toBe(
      "Attach an image or an SVG as a starting point",
    );
  });

  it("hides the input it triggers and accepts exactly the three types", async () => {
    await renderDesign(createHost());

    const input = document.querySelector<HTMLInputElement>(".design-attachment-input");
    expect(input?.getAttribute("type")).toBe("file");
    expect(input?.getAttribute("accept")).toBe(ATTACHMENT_INPUT_ACCEPT);
    expect(input?.hasAttribute("multiple")).toBe(true);
    // Hidden and out of the tab order: one way into the picker, not two.
    expect(input?.hasAttribute("hidden")).toBe(true);
  });

  it("forwards the button's click to the hidden input", async () => {
    const { container } = await renderDesign(createHost());
    const input = document.querySelector<HTMLInputElement>(".design-attachment-input");
    if (input === null) throw new Error("picker input missing");
    const click = vi.spyOn(input, "click");

    await act(async () => {
      document.querySelector<HTMLButtonElement>(".design-attach-button")?.click();
    });

    expect(click).toHaveBeenCalledTimes(1);
    expect(container.querySelector(".design-attachment-pill")).toBeNull();
  });
});

describe("a file dropped on the composer", () => {
  it("shows a pill with its name, type and size", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [imageFile("hero.png", PNG_BYTES, "image/png")],
    });

    expect(pillNames(container)).toEqual(["hero.png"]);
    const pill = container.querySelector(".design-attachment-pill");
    expect(pill?.querySelector(".design-attachment-kind")?.textContent).toBe("PNG");
    expect(pill?.querySelector(".design-attachment-size")?.textContent).toBe(
      formatAttachmentSize(PNG_BYTES.length),
    );
  });

  it("marks the composer while a file is over it and clears the mark on drop", async () => {
    const { container } = await renderDesign(createHost());
    const target = composer(container);

    await dispatchTransferEvent(target, "dragenter", {
      files: [imageFile("hero.png", PNG_BYTES, "image/png")],
    });
    expect(target.getAttribute("data-drop-active")).toBe("true");

    await dispatchTransferEvent(target, "drop", {
      files: [imageFile("hero.png", PNG_BYTES, "image/png")],
    });
    expect(target.hasAttribute("data-drop-active")).toBe(false);
  });

  it("cancels the drop so the window does not navigate to the file", async () => {
    const { container } = await renderDesign(createHost());

    const event = await dispatchTransferEvent(composer(container), "drop", {
      files: [imageFile("hero.png", PNG_BYTES, "image/png")],
    });

    expect(event.defaultPrevented).toBe(true);
  });

  it("ignores a drag that carries no file", async () => {
    const { container } = await renderDesign(createHost());
    const target = composer(container);

    const over = await dispatchTransferEvent(target, "dragover", { types: ["text/plain"] });
    await dispatchTransferEvent(target, "drop", { types: ["text/plain"] });

    expect(over.defaultPrevented).toBe(false);
    expect(target.hasAttribute("data-drop-active")).toBe(false);
    expect(container.querySelector(".design-attachment-pill")).toBeNull();
  });

  it("says so when the drop yielded no file at all, as a folder does", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [],
      items: [{ kind: "file", getAsFile: () => null }],
    });

    expect(feedback(container)).toEqual([
      "One dropped item was not a file, so nothing was attached from it. A folder cannot be attached; drop the image files themselves.",
    ]);
  });

  it("reports the folder in a drop that also carried an image", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [],
      items: [
        { kind: "file", getAsFile: () => imageFile("hero.png", PNG_BYTES, "image/png") },
        { kind: "file", getAsFile: () => null },
      ],
    });

    // The image is attached and the folder is still accounted for.
    expect(pillNames(container)).toEqual(["hero.png"]);
    expect(feedback(container)).toEqual([
      "One dropped item was not a file, so nothing was attached from it. A folder cannot be attached; drop the image files themselves.",
    ]);
  });
});

describe("a paste into the composer", () => {
  it("attaches an image from the clipboard", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(draftField(container), "paste", {
      files: [imageFile("pasted.png", PNG_BYTES, "image/png")],
    });

    expect(pillNames(container)).toEqual(["pasted.png"]);
  });

  it("lets a text paste through untouched", async () => {
    const { container } = await renderDesign(createHost());

    const event = await dispatchTransferEvent(draftField(container), "paste", {
      files: [],
      types: ["text/plain"],
    });

    expect(event.defaultPrevented).toBe(false);
    expect(pillNames(container)).toEqual([]);
  });
});

describe("a file that is not attached", () => {
  it("names the file and the reason", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [
        new File([new Uint8Array([0x25, 0x50, 0x44, 0x46])], "brief.pdf", {
          type: "application/pdf",
        }),
      ],
    });

    expect(pillNames(container)).toEqual([]);
    expect(feedback(container)).toEqual([
      "brief.pdf is a PDF, which this composer does not accept. Export the page as a PNG, or the artwork as an SVG.",
    ]);
    expect(container.querySelector(".design-attachment-error")).not.toBeNull();
  });

  it("reports a sanitized SVG and attaches the sanitized text", async () => {
    const generateMock = vi.fn(async () => ({ ...GENERATION_BASE }));
    const { container } = await renderDesign(createHost({ generate: generateMock }));

    await dispatchTransferEvent(composer(container), "drop", {
      files: [
        new File(
          ['<svg xmlns="http://www.w3.org/2000/svg" onload="x()"><script>1</script><rect/></svg>'],
          "logo.svg",
          { type: "image/svg+xml" },
        ),
      ],
    });

    expect(pillNames(container)).toEqual(["logo.svg"]);
    expect(feedback(container)).toHaveLength(1);
    expect(feedback(container)[0]).toBe(
      "logo.svg was sanitized before attaching: a script and an event handler were removed.",
    );
  });
});

describe("an attached file shows itself in its pill", () => {
  it("draws a raster from the base64 the attachment carries", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [imageFile("hero.png", PNG_BYTES, "image/png")],
    });

    // The expected string is the file's own base64: this PNG carries no metadata
    // chunk, and a file nothing was removed from comes back from the strip as
    // the same bytes rather than as a rebuilt copy.
    const expected = `data:image/png;base64,${btoa(String.fromCharCode(...PNG_BYTES))}`;
    const image = container.querySelector<HTMLImageElement>(".design-attachment-pill img");
    expect(image?.getAttribute("src")?.startsWith("data:image/png;base64,")).toBe(true);
    expect(image?.getAttribute("src")).toBe(expected);
    // The name is beside it and already read aloud; a named image would say it
    // twice, and a lazy data: URL would only defer bytes that are already here.
    expect(image?.getAttribute("alt")).toBe("");
    expect(image?.getAttribute("loading")).toBe("eager");
  });

  it("draws an SVG from its sanitized source, percent-encoded rather than base64", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [
        new File(
          [
            '<svg xmlns="http://www.w3.org/2000/svg"><script>1</script><rect width="4" height="4"/></svg>',
          ],
          "mark.svg",
          { type: "image/svg+xml" },
        ),
      ],
    });

    const src =
      container
        .querySelector<HTMLImageElement>(".design-attachment-pill img")
        ?.getAttribute("src") ?? "";
    expect(src.startsWith("data:image/svg+xml,")).toBe(true);
    // The source is carried as text: the tags are percent-encoded, so the
    // attribute holds no `<script` for anything downstream to find, and none was
    // in the sanitized source to begin with.
    expect(src).not.toContain("<script");
    expect(src).toContain("%3Csvg");
  });

  it("keeps a preview for an SVG whose title is not ASCII", async () => {
    // This is the case that decides the encoding. `btoa` takes only Latin-1 and
    // the sanitized source is UTF-8, so base64-ing this file would throw where
    // its data: URL is built and the preview would vanish on a file that is
    // entirely fine. Percent-encoding carries the same characters, so the src
    // exists and decodes back to the title that was written.
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [
        new File(
          ['<svg xmlns="http://www.w3.org/2000/svg"><title>Café résumé</title><rect/></svg>'],
          "cafe.svg",
          { type: "image/svg+xml" },
        ),
      ],
    });

    const src =
      container
        .querySelector<HTMLImageElement>(".design-attachment-pill img")
        ?.getAttribute("src") ?? "";
    const prefix = "data:image/svg+xml,";
    expect(src.startsWith(prefix)).toBe(true);
    const decoded = decodeURIComponent(src.slice(prefix.length));
    expect(decoded).toContain("Café résumé");
    // The accented characters travel as UTF-8 percent-encodings, never as
    // themselves, which is what keeps the attribute a valid URL.
    expect(src).not.toContain("é");
  });

  it("keeps the slot and names the file when the preview cannot be drawn", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [imageFile("hero.png", PNG_BYTES, "image/png")],
    });

    const image = container.querySelector<HTMLImageElement>(".design-attachment-pill img");
    if (image === null) throw new Error("preview missing");
    await act(async () => {
      image.dispatchEvent(new Event("error"));
    });

    // Emptied, not hidden. A preview that disappeared on failure would make a
    // file the renderer choked on indistinguishable from a healthy one, which is
    // the only thing this element is here to tell apart.
    const empty = container.querySelector(".design-attachment-preview-empty");
    expect(container.querySelector(".design-attachment-pill img")).toBeNull();
    expect(empty?.getAttribute("aria-label")).toBe("Preview unavailable");
    expect(empty?.getAttribute("title")).toBe("Preview unavailable");
    // A notice and not an error: the file is attached, and the sentence says so
    // by naming it in the same place the import's own notes arrive.
    expect(feedback(container)).toEqual([
      "hero.png was attached, but its preview could not be drawn.",
    ]);
    // The pill lost none of what it said before.
    const pill = container.querySelector(".design-attachment-pill");
    expect(pillNames(container)).toEqual(["hero.png"]);
    expect(pill?.querySelector(".design-attachment-kind")?.textContent).toBe("PNG");
    expect(pill?.querySelector(".design-attachment-size")?.textContent).toBe(
      formatAttachmentSize(PNG_BYTES.length),
    );
  });

  it("gives four attachments four previews without disturbing the row", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [
        imageFile("one.png", PNG_BYTES, "image/png"),
        imageFile("two.png", PNG_BYTES, "image/png"),
        imageFile("three.png", PNG_BYTES, "image/png"),
        new File([CLEAN_SVG], "four.svg", { type: "image/svg+xml" }),
      ],
    });

    expect(pillNames(container)).toEqual(["one.png", "two.png", "three.png", "four.svg"]);
    expect(container.querySelectorAll(".design-attachment-pill img")).toHaveLength(4);
    // One preview per pill, ahead of the name, so the row keeps the arrangement
    // the rest of these tests describe.
    for (const pill of container.querySelectorAll(".design-attachment-pill")) {
      const preview = pill.querySelector(".design-attachment-preview");
      expect(preview?.nextElementSibling?.classList.contains("design-attachment-name")).toBe(true);
    }
    expect(
      notice(container)?.previousElementSibling?.classList.contains("design-attachment-row"),
    ).toBe(true);
  });
});

describe("the composer says what it will not send", () => {
  it("shows the delivery notice beside the pills as soon as one file is attached", async () => {
    const { container } = await renderDesign(createHost());
    expect(notice(container)).toBeNull();

    await dispatchTransferEvent(composer(container), "drop", {
      files: [imageFile("hero.png", PNG_BYTES, "image/png")],
    });

    const element = notice(container);
    expect(element?.textContent).toBe(ATTACHMENT_DELIVERY_NOTICE);
    // In the composer, directly after the row of pills: the sentence has to be
    // read at the moment of attaching, not found after a wasted run.
    expect(element?.parentElement?.classList.contains("design-composer")).toBe(true);
    expect(element?.previousElementSibling?.classList.contains("design-attachment-row")).toBe(true);
    // Visible text, not an accessible name on an invisible node and not a tooltip.
    expect(element?.hasAttribute("title")).toBe(false);
    expect(element?.getAttribute("aria-label")).toBeNull();
    expect(element?.textContent?.length).toBeGreaterThan(0);
  });

  it("carries the three facts the pills leave out, as a note rather than an error", async () => {
    // The sentence is the deliverable, so its meaning is asserted directly: it
    // must say the file is held, that it is not sent, and why. A rewrite that
    // drops one of the three turns the notice into decoration.
    expect(ATTACHMENT_DELIVERY_NOTICE).toMatch(/kept here/);
    expect(ATTACHMENT_DELIVERY_NOTICE).toMatch(/not sent/);
    expect(ATTACHMENT_DELIVERY_NOTICE).toMatch(/text only/);

    const { container } = await renderDesign(createHost());
    await dispatchTransferEvent(composer(container), "drop", {
      files: [
        imageFile("hero.png", PNG_BYTES, "image/png"),
        imageFile("detail.png", PNG_BYTES, "image/png"),
      ],
    });

    const element = notice(container);
    expect(element?.classList.contains("design-attachment-error")).toBe(false);
    expect(element?.className).toBe("design-attachment-notice");
    // role=status: a reader without sight learns it when it appears, not never.
    expect(element?.getAttribute("role")).toBe("status");
  });

  it("takes the notice away with the last attachment", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [imageFile("hero.png", PNG_BYTES, "image/png")],
    });
    expect(notice(container)).not.toBeNull();

    const remove = container.querySelector<HTMLButtonElement>(
      'button[aria-label="Remove hero.png"]',
    );
    if (remove === null) throw new Error("remove control missing");
    await act(async () => remove.click());

    expect(pillNames(container)).toEqual([]);
    expect(notice(container)).toBeNull();
  });
});

describe("an attached file reaches the host and then leaves the composer", () => {
  it("carries the attachment on the generation options and clears the pill", async () => {
    // The mock declares the three parameters the host is called with, so the
    // options argument can be read back and asserted on directly.
    const generateMock = vi.fn(
      async (_prompt: string, _signal: AbortSignal, _options?: DesignGenerationOptions) => ({
        ...GENERATION_BASE,
      }),
    );
    const { container } = await renderDesign(createHost({ generate: generateMock }));

    await dispatchTransferEvent(composer(container), "drop", {
      files: [
        imageFile("hero.png", PNG_BYTES, "image/png"),
        new File([CLEAN_SVG], "mark.svg", { type: "image/svg+xml" }),
      ],
    });
    expect(pillNames(container)).toEqual(["hero.png", "mark.svg"]);

    await fillDraft(container, "Build the landing page around this.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => {
      send.click();
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(generateMock).toHaveBeenCalledTimes(1);
    const options = generateMock.mock.calls[0]?.[2];
    expect(options?.attachments).toHaveLength(2);
    expect(options?.attachments?.[0]).toMatchObject({ kind: "raster", name: "hero.png" });
    expect(options?.attachments?.[1]).toMatchObject({ kind: "svg", name: "mark.svg" });
    // Cleared with the draft: a second run must not resend the first run's files.
    expect(pillNames(container)).toEqual([]);
  });

  it("does not let an import started before a run re-add the files it consumed", async () => {
    let releaseRead: (() => void) | null = null;
    const readGate = new Promise<void>((resolve) => {
      releaseRead = resolve;
    });
    const slowFile = new File([PNG_BYTES], "hero.png", { type: "image/png" });
    // The read parks until the test lets it finish, which is what puts the
    // import in flight across the start of the run.
    Object.defineProperty(slowFile, "arrayBuffer", {
      value: async () => {
        await readGate;
        return PNG_BYTES.buffer.slice(0);
      },
    });

    const generateMock = vi.fn(
      async (_prompt: string, _signal: AbortSignal, _options?: DesignGenerationOptions) => ({
        ...GENERATION_BASE,
      }),
    );
    const { container } = await renderDesign(createHost({ generate: generateMock }));

    // 1. The import starts and parks on the file read.
    await dispatchTransferEvent(composer(container), "drop", { files: [slowFile] });
    expect(pillNames(container)).toEqual([]);

    // 2. The run starts and consumes the composer (the empty list is what it
    //    carries; the files dropped a moment ago were never attached).
    await fillDraft(container, "Build the page.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => {
      send.click();
      await Promise.resolve();
    });
    expect(generateMock.mock.calls[0]?.[2]?.attachments).toEqual([]);

    // 3. The read finishes after the run began: the import measured a composer
    //    that no longer exists, so its result — the files and the feedback
    //    about them — belongs to nothing and is dropped.
    await act(async () => {
      releaseRead?.();
      await readGate;
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    expect(pillNames(container)).toEqual([]);
    expect(feedback(container)).toEqual([]);
  });

  it("drops one attachment when its remove control is used", async () => {
    const { container } = await renderDesign(createHost());

    await dispatchTransferEvent(composer(container), "drop", {
      files: [
        imageFile("hero.png", PNG_BYTES, "image/png"),
        imageFile("detail.png", PNG_BYTES, "image/png"),
      ],
    });
    expect(pillNames(container)).toEqual(["hero.png", "detail.png"]);

    const remove = container.querySelector<HTMLButtonElement>(
      'button[aria-label="Remove hero.png"]',
    );
    if (remove === null) throw new Error("remove control missing");
    await act(async () => remove.click());

    expect(pillNames(container)).toEqual(["detail.png"]);
  });
});
