// @vitest-environment happy-dom

import { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useAppStore } from "../../store/appStore";
import { builtInSkillIndex } from "./builtInSkills";

const skillSettingsMocks = vi.hoisted(() => ({
  load: vi.fn(),
  save: vi.fn(),
}));

vi.mock("./designSettings", async () => {
  const actual = await vi.importActual<typeof import("./designSettings")>("./designSettings");
  return {
    ...actual,
    loadDesignSkillSelection: skillSettingsMocks.load,
    saveDesignSkillSelection: skillSettingsMocks.save,
  };
});

import {
  createViewport,
  fitViewport,
  panViewport,
  viewportTransform,
  zoomViewport,
} from "./designViewport";
import { DesignSurface, type DesignDocument, type DesignHost } from "./DesignSurface";
import type { DesignGenerationResult } from "./designHost";
import { MAX_ARTIFACT_BYTES } from "./agentHost";
import { nodesBounds } from "../../lib/canvas/viewportMath";
import { rectIntersects } from "../../lib/canvas/hitTest";
import type { NodeRect } from "../../types/geometry";

(
  globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

const DOCUMENT: DesignDocument = {
  name: "Index browser",
  path: "~/dev/devboule/src/design",
  provider: "Claude Code · High",
  contextPrefix: "Editing",
  draftPlaceholder: "Describe the change to Index header…",
  noContextPlaceholder: "Describe what to generate…",
  tokenFooter: "Values snap to design tokens (DTCG)",
  selectedLayerId: "index-header",
  grounded: true,
  initialState: {
    tool: "move",
    zoom: 1,
    radius: 14,
    flat: false,
    saved: false,
    draft: "",
    hiddenLayerIds: [],
  },
  layers: [
    {
      id: "index-header",
      name: "Index header",
      kind: "TSX",
      transform: { x: 396, y: 92, width: 336, height: 198, hug: true },
    },
    {
      id: "stale-queue",
      name: "Stale queue",
      kind: "TSX",
      transform: { x: 60, y: 46, width: 300, height: 124 },
    },
  ],
  canvasContent: {
    aiRegion: { x: 420, y: 300, width: 240, height: 96, actionLabel: "Analyze this region" },
  },
  radiusOptions: [
    { token: "none", value: 0 },
    { token: "sm", value: 8 },
    { token: "md", value: 14 },
    { token: "lg", value: 22 },
  ],
  messages: [
    {
      id: "message-0",
      role: "user",
      text: "Use the real stale count in the header.",
    },
    {
      id: "message-1",
      role: "assistant",
      status: "done",
      title: "Edited Index header",
      desc: "Applied the edit.",
      sources: [],
      nodeIds: ["index-header"],
    },
  ],
  workingMessage: {
    title: "Generating…",
    desc: "Reading the grounded files, then writing the node.",
  },
};

const GENERATION_RESULT = {
  prompt: "host echo",
  title: "Generated result",
  desc: "Generated by the host.",
  sources: ["host.ts"],
  nodeIds: ["index-header"],
};

const ARTIFACT_RESULT = {
  ...GENERATION_RESULT,
  artifactHtml: '<main class="generated-card">Generated</main>',
};

const ARTIFACT_ERROR_RESULT = {
  ...GENERATION_RESULT,
  artifactError: "Artifact too large to display (maximum 256 KiB).",
};

const ARTIFACT_CSP_META =
  "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'none'; font-src 'none'; connect-src 'none'; form-action 'none'; base-uri 'none'; frame-src 'none'; object-src 'none'; media-src 'none'; worker-src 'none'; manifest-src 'none'\" />";

function createHost(
  overrides: Partial<DesignHost> = {},
  document: DesignDocument = DOCUMENT,
): DesignHost {
  return {
    loadDocument: vi.fn(async () => document),
    ...overrides,
  };
}

function pointerEvent(
  type: string,
  init: { button?: number; clientX?: number; clientY?: number; pointerId: number },
): MouseEvent {
  const event = new MouseEvent(type, {
    bubbles: true,
    button: init.button,
    clientX: init.clientX,
    clientY: init.clientY,
  });
  Object.defineProperty(event, "pointerId", { value: init.pointerId });
  return event;
}

function wheelEvent(init: {
  clientX: number;
  clientY: number;
  deltaMode: number;
  deltaY: number;
}): WheelEvent {
  const event = new Event("wheel", { bubbles: true, cancelable: true }) as WheelEvent;
  Object.defineProperties(event, {
    clientX: { value: init.clientX },
    clientY: { value: init.clientY },
    deltaMode: { value: init.deltaMode },
    deltaY: { value: init.deltaY },
  });
  return event;
}

async function fillDraft(container: HTMLDivElement, prompt: string): Promise<HTMLTextAreaElement> {
  const draft = container.querySelector<HTMLTextAreaElement>(
    'textarea[aria-label="Describe a design change"]',
  );
  if (draft === null) throw new Error("Design composer missing");
  const setValue = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set;
  if (setValue === undefined) throw new Error("textarea value setter did not exist");

  await act(async () => {
    setValue.call(draft, prompt);
    draft.dispatchEvent(new Event("input", { bubbles: true }));
  });
  return draft;
}

async function renderDesign(host: DesignHost): Promise<{
  container: HTMLDivElement;
  root: ReturnType<typeof createRoot>;
}> {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root = createRoot(container);
  await act(async () => {
    root.render(<DesignSurface host={host} />);
  });
  return { container, root };
}

beforeEach(() => {
  useAppStore.setState({ plugins: null, installing: null, installError: null });
  skillSettingsMocks.load.mockReset();
  skillSettingsMocks.save.mockReset();
  skillSettingsMocks.load.mockResolvedValue({ version: 1, mode: "all", enabledSlugs: [] });
  skillSettingsMocks.save.mockResolvedValue(undefined);
});

afterEach(() => {
  document.body.replaceChildren();
});

describe("DesignSurface host capabilities", () => {
  it("omits the save control when the host is view-only", async () => {
    const { container, root } = await renderDesign(createHost());

    expect(container.querySelector(".design-save-primary")).toBeNull();
    expect(container.querySelector(".design-save-menu")).toBeNull();
    await act(async () => root.unmount());
  });

  it("calls the host exactly once with the loaded document when saving", async () => {
    const saveDocument = vi.fn(async (_document: DesignDocument) => undefined);
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (save === null) throw new Error("Save control missing");

    await act(async () => save.click());

    expect(saveDocument).toHaveBeenCalledTimes(1);
    expect(saveDocument).toHaveBeenCalledWith(DOCUMENT);
    await act(async () => root.unmount());
  });

  it("does not dirty a saved document when selecting its already-selected layer", async () => {
    const saveDocument = vi.fn(async (_document: DesignDocument) => undefined);
    const savedDocument: DesignDocument = {
      ...DOCUMENT,
      initialState: { ...DOCUMENT.initialState, saved: true },
    };
    const { container, root } = await renderDesign(createHost({ saveDocument }, savedDocument));
    const selectedLayer = container.querySelector<HTMLButtonElement>(
      '[aria-label="Select Index header"]',
    );
    if (selectedLayer === null) throw new Error("Selected layer missing");

    expect(container.querySelector(".design-save-status")?.textContent).toContain("Saved");
    await act(async () => selectedLayer.click());

    expect(container.querySelector(".design-save-status")?.textContent).toContain("Saved");
    expect(container.querySelector(".design-save-status")?.textContent).not.toContain(
      "Unsaved changes",
    );
    await act(async () => root.unmount());
  });

  it("saves the current on-screen snapshot rather than the loaded snapshot", async () => {
    const saveDocument = vi.fn(async (_document: DesignDocument) => undefined);
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const radius = container.querySelector<HTMLButtonElement>(
      '[aria-label="Set radius.sm, 8 pixels"]',
    );
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (radius === null || save === null) throw new Error("Save controls missing");

    await act(async () => radius.click());
    await act(async () => save.click());

    const savedDocument = saveDocument.mock.calls[0]?.[0];
    expect(savedDocument?.initialState.radius).toBe(8);
    await act(async () => root.unmount());
  });

  it("keeps the document dirty when an edit lands during a save", async () => {
    let resolveSave: (() => void) | undefined;
    const saveDocument = vi.fn(
      () =>
        new Promise<void>((resolve) => {
          resolveSave = resolve;
        }),
    );
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const radius = container.querySelector<HTMLButtonElement>(
      '[aria-label="Set radius.sm, 8 pixels"]',
    );
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (radius === null || save === null) throw new Error("Save controls missing");

    await act(async () => radius.click());
    await act(async () => save.click());
    const undo = container.querySelector<HTMLButtonElement>('[aria-label="Undo"]');
    if (undo === null || resolveSave === undefined) throw new Error("Save race controls missing");

    await act(async () => undo.click());
    await act(async () => {
      resolveSave?.();
      await Promise.resolve();
    });

    expect(container.querySelector(".design-save-status")?.textContent).toContain(
      "Unsaved changes",
    );
    await act(async () => root.unmount());
  });

  it("surfaces save failures without claiming that the document was saved", async () => {
    const saveDocument = vi.fn(async () => {
      throw new Error("Repository unavailable");
    });
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (save === null) throw new Error("Save control missing");

    await act(async () => save.click());

    expect(container.querySelector('[role="alert"]')?.textContent).toContain(
      "Repository unavailable",
    );
    expect(container.querySelector(".design-save-status")?.textContent).not.toContain("Saved");
    await act(async () => root.unmount());
  });

  it("clears an earlier save error after a later save succeeds", async () => {
    const saveDocument = vi
      .fn<NonNullable<DesignHost["saveDocument"]>>()
      .mockRejectedValueOnce(new Error("Repository unavailable"))
      .mockResolvedValueOnce(undefined);
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (save === null) throw new Error("Save control missing");

    await act(async () => save.click());
    expect(container.querySelector('[role="alert"]')?.textContent).toContain(
      "Repository unavailable",
    );
    await act(async () => save.click());

    expect(container.querySelector('[role="alert"]')).toBeNull();
    expect(container.querySelector(".design-save-status")?.textContent).toContain("Saved");
    await act(async () => root.unmount());
  });

  it("does not offer canvas selection when a result has no node", async () => {
    const assistantMessage = DOCUMENT.messages[1];
    if (assistantMessage?.role !== "assistant") throw new Error("Assistant fixture missing");
    const documentWithoutNode = {
      ...DOCUMENT,
      messages: [DOCUMENT.messages[0]!, { ...assistantMessage, nodeIds: [] }],
    } satisfies DesignDocument;
    const generate = vi.fn(async () => ({ ...GENERATION_RESULT, nodeIds: [] }));
    const { container, root } = await renderDesign(createHost({ generate }, documentWithoutNode));

    expect(
      Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
        (button) => button.textContent === "Select on canvas",
      ),
    ).toBeUndefined();

    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(
      Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
        (button) => button.textContent === "Select on canvas",
      ),
    ).toBeUndefined();
    await act(async () => root.unmount());
  });

  it("persists the selected layer and grounding preference", async () => {
    let savedDocument: DesignDocument | undefined;
    const saveDocument = vi.fn(async (next: DesignDocument) => {
      savedDocument = next;
    });
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const staleQueue = container.querySelector<HTMLButtonElement>(
      '[aria-label="Select Stale queue"]',
    );
    const grounding = container.querySelector<HTMLButtonElement>(".design-grounding-toggle");
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (staleQueue === null || grounding === null || save === null) {
      throw new Error("Document controls missing");
    }

    await act(async () => staleQueue.click());
    await act(async () => grounding.click());
    await act(async () => save.click());

    expect(savedDocument?.selectedLayerId).toBe("stale-queue");
    expect(savedDocument?.grounded).toBe(false);
    await act(async () => root.unmount());

    if (savedDocument === undefined) throw new Error("Save did not produce a document");
    const reloaded = await renderDesign(createHost({}, savedDocument));
    expect(
      reloaded.container
        .querySelector<HTMLButtonElement>('[aria-label="Select Stale queue"]')
        ?.getAttribute("aria-pressed"),
    ).toBe("true");
    expect(
      reloaded.container
        .querySelector<HTMLButtonElement>(".design-grounding-toggle")
        ?.getAttribute("aria-pressed"),
    ).toBe("false");
    await act(async () => reloaded.root.unmount());
  });

  it("normalizes a working message found in a loaded document", async () => {
    const assistantMessage = DOCUMENT.messages[1];
    if (assistantMessage?.role !== "assistant") throw new Error("Assistant fixture missing");
    const workingDocument = {
      ...DOCUMENT,
      messages: [
        DOCUMENT.messages[0]!,
        { ...assistantMessage, status: "working" as const, title: "Generating…" },
      ],
    } satisfies DesignDocument;
    const { container, root } = await renderDesign(createHost({}, workingDocument));

    expect(container.textContent).toContain("Generation incomplete");
    expect(
      Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
        (button) => button.textContent === "Stop",
      ),
    ).toBeUndefined();
    await act(async () => root.unmount());
  });

  it("turns a working generation into a terminal message before saving and reload", async () => {
    let savedDocument: DesignDocument | undefined;
    const generate = vi.fn(() => new Promise<DesignGenerationResult>(() => undefined));
    const saveDocument = vi.fn(async (next: DesignDocument) => {
      savedDocument = next;
    });
    const { container, root } = await renderDesign(createHost({ generate, saveDocument }));
    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (send === null || save === null) throw new Error("Generation controls missing");

    await act(async () => send.click());
    expect(container.textContent).toContain("Generating…");
    await act(async () => save.click());

    if (savedDocument === undefined) throw new Error("Save did not produce a document");
    expect(
      savedDocument.messages.some(
        (message) => message.role === "assistant" && message.status === "working",
      ),
    ).toBe(false);
    expect(container.querySelector(".design-save-status")?.textContent).toContain(
      "Unsaved changes",
    );
    await act(async () => root.unmount());

    const reloaded = await renderDesign(createHost({ generate }, savedDocument));
    expect(reloaded.container.textContent).toContain("Generation incomplete");
    expect(
      Array.from(reloaded.container.querySelectorAll<HTMLButtonElement>("button")).find(
        (button) => button.textContent === "Stop",
      ),
    ).toBeUndefined();
    await act(async () => reloaded.root.unmount());
  });

  it("rejects a second save before the first save renders its state", async () => {
    let resolveSave: (() => void) | undefined;
    const saveDocument = vi.fn(
      () =>
        new Promise<void>((resolve) => {
          resolveSave = resolve;
        }),
    );
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (save === null) throw new Error("Save control missing");

    await act(async () => {
      save.click();
      save.click();
    });

    expect(saveDocument).toHaveBeenCalledTimes(1);
    resolveSave?.();
    await act(async () => undefined);
    await act(async () => root.unmount());
  });

  it("shows a load failure instead of rendering an empty document", async () => {
    const host = createHost({
      loadDocument: vi.fn(async () => {
        throw new Error("Document unavailable");
      }),
    });
    const { container, root } = await renderDesign(host);

    expect(container.querySelector('[role="alert"]')?.textContent).toContain(
      "Document unavailable",
    );
    expect(container.querySelector(".design-toolbar")).toBeNull();
    await act(async () => root.unmount());
  });

  it("shows a generation failure in the assistant", async () => {
    const generate = vi.fn(async () => {
      throw new Error("Generation unavailable");
    });
    const { container, root } = await renderDesign(createHost({ generate }));
    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");

    await act(async () => send.click());

    expect(generate).toHaveBeenCalledTimes(1);
    expect(container.textContent).toContain("Generation failed");
    expect(container.textContent).toContain("Generation unavailable");
    await act(async () => root.unmount());
  });

  it("applies a generation result as soon as the host resolves", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }));
    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");

    await act(async () => send.click());

    expect(container.textContent).toContain("Generated result");
    expect(container.textContent).not.toContain("Generating…");
    expect(container.querySelector("iframe")).toBeNull();
    await act(async () => root.unmount());
  });

  it("sends the selected layer scope shown by the composer chip", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }));
    expect(container.querySelector(".design-composer-context")?.textContent).toContain(
      "Editing Index header",
    );

    await fillDraft(container, "Make the header quieter.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(generate).toHaveBeenCalledWith(
      'Make the header quieter.\n\nScope: Editing Index header (TSX); the user is pointing at the layer named "Index header".',
      expect.any(AbortSignal),
      { skills: expect.any(Array) },
    );
    await act(async () => root.unmount());
  });

  it("does not send a scope when nothing is selected", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const noSelectionDocument = { ...DOCUMENT, selectedLayerId: "" };
    const { container, root } = await renderDesign(createHost({ generate }, noSelectionDocument));
    expect(container.querySelector(".design-composer-context")).toBeNull();

    await fillDraft(container, "Make the header quieter.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(generate).toHaveBeenCalledWith("Make the header quieter.", expect.any(AbortSignal), {
      skills: expect.any(Array),
    });
    await act(async () => root.unmount());
  });

  it("sends the selected layer source path in the scope", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const sourceDocument: DesignDocument = {
      ...DOCUMENT,
      selectedLayerId: "source-header",
      layers: [
        {
          ...DOCUMENT.layers[0]!,
          id: "source-header",
          name: "Source header",
          source: { path: "src/components/Header.tsx" },
        },
      ],
    };
    const { container, root } = await renderDesign(createHost({ generate }, sourceDocument));

    await fillDraft(container, "Make this quieter.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(generate).toHaveBeenCalledWith(
      expect.stringContaining("source file: src/components/Header.tsx"),
      expect.any(AbortSignal),
      { skills: expect.any(Array) },
    );
    await act(async () => root.unmount());
  });

  it("shows a truthful notice when no repository layers were found", async () => {
    const emptyDocument: DesignDocument = {
      ...DOCUMENT,
      selectedLayerId: "",
      layers: [],
      layerNotice: "No TSX or SVG components found in the indexed workspace.",
    };
    const { container, root } = await renderDesign(createHost({}, emptyDocument));

    expect(container.querySelector(".design-canvas-empty")?.textContent).toBe(
      "No TSX or SVG components found in the indexed workspace.",
    );
    expect(container.querySelector(".design-layer-count")?.textContent).toBe("0");
    await act(async () => root.unmount());
  });

  it("shows a partial-list notice above layers without intercepting canvas input", async () => {
    const documentWithPartialNotice: DesignDocument = {
      ...DOCUMENT,
      layerNotice: "Oracle's component list is partial; showing the first 36 layers.",
    };
    const { container, root } = await renderDesign(createHost({}, documentWithPartialNotice));

    const notice = container.querySelector<HTMLElement>('.design-canvas-notice[role="status"]');
    if (notice === null) throw new Error("Partial-list notice missing");
    expect(notice.textContent).toContain("component list is partial");
    expect(getComputedStyle(notice).zIndex).toBe("1");
    expect(getComputedStyle(notice).pointerEvents).toBe("none");
    await act(async () => root.unmount());
  });

  it("shows a repository source directory instead of invented dimensions", async () => {
    const sourceDocument: DesignDocument = {
      ...DOCUMENT,
      layers: [
        {
          ...DOCUMENT.layers[0]!,
          source: { path: "src/components/Header.tsx" },
        },
        DOCUMENT.layers[1]!,
      ],
    };
    const { container, root } = await renderDesign(createHost({}, sourceDocument));

    const sourceNode = container.querySelector<HTMLButtonElement>(
      '[aria-label="Select Index header"]',
    );
    const fixtureNode = container.querySelector<HTMLButtonElement>(
      '[aria-label="Select Stale queue"]',
    );
    if (sourceNode === null || fixtureNode === null) throw new Error("Canvas layers missing");
    expect(sourceNode.textContent).toContain("src/components");
    expect(sourceNode.textContent).not.toContain("336 × 198");
    expect(fixtureNode.textContent).not.toContain("300 × 124");
    expect(fixtureNode.textContent).not.toContain("World layer");
    await act(async () => root.unmount());
  });

  it("does not offer Duplicate for a repository-backed layer", async () => {
    const sourceDocument: DesignDocument = {
      ...DOCUMENT,
      layers: [
        {
          ...DOCUMENT.layers[0]!,
          source: { path: "src/components/Header.tsx" },
        },
        DOCUMENT.layers[1]!,
      ],
    };
    const { container, root } = await renderDesign(createHost({}, sourceDocument));

    expect(
      Array.from(container.querySelectorAll("button")).find(
        (button) => button.textContent === "Duplicate",
      ),
    ).toBeUndefined();
    await act(async () => root.unmount());
  });

  it("places the generated artifact below every layer rectangle", async () => {
    const layers = Array.from({ length: 12 }, (_, index) => ({
      ...DOCUMENT.layers[0]!,
      id: `grid-layer-${index}`,
      name: `Grid layer ${index}`,
      transform: {
        x: 60 + (index % 4) * 312,
        y: 46 + Math.floor(index / 4) * 172,
        width: 280,
        height: 140,
      },
    }));
    const gridDocument: DesignDocument = { ...DOCUMENT, selectedLayerId: "", layers };
    const generate = vi.fn(async () => ARTIFACT_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }, gridDocument));
    await fillDraft(container, "Create the first pass.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    const artifact = container.querySelector<HTMLElement>(".design-canvas-artifact");
    if (artifact === null) throw new Error("Generated artifact missing");
    const artifactRect: NodeRect = {
      id: "generated-artifact",
      x: Number.parseFloat(artifact.style.left),
      y: Number.parseFloat(artifact.style.top),
      w: Number.parseFloat(artifact.style.width),
      h: Number.parseFloat(artifact.style.height),
      z: layers.length,
    };
    for (const node of container.querySelectorAll<HTMLElement>(".design-canvas-node")) {
      const layerRect: NodeRect = {
        id: node.dataset.canvasLayerId ?? "",
        x: Number.parseFloat(node.style.left),
        y: Number.parseFloat(node.style.top),
        w: Number.parseFloat(node.style.width),
        h: Number.parseFloat(node.style.height),
        z: 0,
      };
      expect(rectIntersects(artifactRect, layerRect)).toBe(false);
    }
    await act(async () => root.unmount());
  });

  it("selects the artifact, scopes the next prompt to it, and clears on empty canvas", async () => {
    const generate = vi.fn(async () => ARTIFACT_RESULT);
    const noSelectionDocument = { ...DOCUMENT, selectedLayerId: "" };
    const { container, root } = await renderDesign(createHost({ generate }, noSelectionDocument));
    await fillDraft(container, "Create the first pass.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    const artifact = container.querySelector<HTMLDivElement>(".design-canvas-artifact");
    const stage = container.querySelector<HTMLDivElement>(".design-canvas-stage");
    if (artifact === null || stage === null) {
      throw new Error("Generated artifact or canvas stage missing");
    }
    const iframe = artifact.querySelector<HTMLIFrameElement>("iframe");
    if (iframe === null) throw new Error("Generated artifact frame missing");
    expect(iframe.style.pointerEvents).toBe("none");
    expect(iframe.getAttribute("sandbox")).toBe("");
    expect(artifact.querySelector(".design-canvas-artifact-content")?.hasAttribute("inert")).toBe(
      true,
    );

    await act(async () => {
      artifact.dispatchEvent(
        new MouseEvent("click", { bubbles: true, clientX: 100, clientY: 500 }),
      );
    });
    expect(artifact.classList.contains("design-canvas-artifact-selected")).toBe(true);
    expect(container.querySelector(".design-composer-context")?.textContent).toContain(
      "Editing Generated artifact",
    );
    expect(container.querySelector(".design-inspector-panel")).toBeNull();

    await act(async () => {
      artifact.dispatchEvent(new KeyboardEvent("keydown", { bubbles: true, key: "Enter" }));
    });
    expect(artifact.classList.contains("design-canvas-artifact-selected")).toBe(true);

    await fillDraft(container, "Refine this artifact.");
    await act(async () => send.click());
    expect(generate).toHaveBeenLastCalledWith(
      "Refine this artifact.\n\nScope: Editing Generated artifact; the user is refining the artifact the agent just produced.",
      expect.any(AbortSignal),
      { skills: expect.any(Array) },
    );

    await act(async () => {
      stage.dispatchEvent(new MouseEvent("click", { bubbles: true, clientX: 900, clientY: 900 }));
    });
    expect(artifact.classList.contains("design-canvas-artifact-selected")).toBe(false);
    expect(container.querySelector(".design-composer-context")).toBeNull();
    await act(async () => root.unmount());
  });

  it("prefixes the artifact with its own CSP before any artifact markup", async () => {
    const artifactHtml =
      '<meta http-equiv="Content-Security-Policy" content="default-src *"><main>Generated</main>';
    const generate = vi.fn(async () => ({ ...GENERATION_RESULT, artifactHtml }));
    const { container, root } = await renderDesign(
      createHost({ generate }, { ...DOCUMENT, selectedLayerId: "" }),
    );
    await fillDraft(container, "Create a constrained first pass.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    const iframe = container.querySelector<HTMLIFrameElement>("iframe");
    if (iframe === null) throw new Error("Generated artifact frame missing");
    const srcDoc = iframe.getAttribute("srcdoc");
    if (srcDoc === null) throw new Error("Generated artifact source missing");
    expect(srcDoc.startsWith(`${ARTIFACT_CSP_META}\n`)).toBe(true);
    expect(srcDoc.indexOf('content="default-src *"')).toBeGreaterThan(ARTIFACT_CSP_META.length);
    expect(srcDoc).toBe(`${ARTIFACT_CSP_META}\n${artifactHtml}`);
    await act(async () => root.unmount());
  });

  it("measures the cap on the artifact without counting the CSP prefix", async () => {
    const artifactHtml = "x".repeat(MAX_ARTIFACT_BYTES);
    const generate = vi.fn(async () => ({ ...GENERATION_RESULT, artifactHtml }));
    const { container, root } = await renderDesign(
      createHost({ generate }, { ...DOCUMENT, selectedLayerId: "" }),
    );
    await fillDraft(container, "Create a maximum-size first pass.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    const iframe = container.querySelector<HTMLIFrameElement>("iframe");
    if (iframe === null) throw new Error("Artifact at the cap was not rendered");
    const srcDoc = iframe.getAttribute("srcdoc");
    if (srcDoc === null) throw new Error("Generated artifact source missing");
    expect(srcDoc.endsWith(artifactHtml)).toBe(true);
    expect(srcDoc.length).toBeGreaterThan(MAX_ARTIFACT_BYTES);
    await act(async () => root.unmount());
  });

  it("shows an explicit artifact display error instead of mounting an oversized frame", async () => {
    const generate = vi.fn(async () => ARTIFACT_ERROR_RESULT);
    const { container, root } = await renderDesign(
      createHost({ generate }, { ...DOCUMENT, selectedLayerId: "" }),
    );
    await fillDraft(container, "Create a very large first pass.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(container.querySelector(".design-canvas-artifact-error")?.textContent).toBe(
      "Artifact too large to display (maximum 256 KiB).",
    );
    expect(container.querySelector("iframe")).toBeNull();
    await act(async () => root.unmount());
  });

  it("shows missing artifact tokens without calling the artifact broken", async () => {
    const generate = vi.fn(async () => ({
      ...GENERATION_RESULT,
      artifactHtml: "<style>.card { color: var(--missing-ink); }</style><main>Generated</main>",
    }));
    const { container, root } = await renderDesign(
      createHost({ generate }, { ...DOCUMENT, selectedLayerId: "" }),
    );
    await fillDraft(container, "Create a token-aware first pass.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    const warning = container.querySelector<HTMLElement>(
      '[role="status"].design-canvas-artifact-token-warning',
    );
    if (warning === null) throw new Error("Missing-token warning missing");
    expect(warning.textContent).toContain("references a token it does not define: --missing-ink");
    expect(container.textContent).not.toContain("artifact is broken");
    await act(async () => root.unmount());
  });

  it("does not render an empty missing-token notice for a complete artifact", async () => {
    const generate = vi.fn(async () => ({
      ...GENERATION_RESULT,
      artifactHtml: "<style>.card { color: red; }</style><main>Generated</main>",
    }));
    const { container, root } = await renderDesign(
      createHost({ generate }, { ...DOCUMENT, selectedLayerId: "" }),
    );
    await fillDraft(container, "Create a complete first pass.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(container.querySelector(".design-canvas-artifact-token-warning")).toBeNull();
    await act(async () => root.unmount());
  });

  it("aborts a pending generation and reports an actual cancellation", async () => {
    let generationSignal: AbortSignal | undefined;
    const generate = vi.fn(
      (_prompt: string, signal: AbortSignal) =>
        new Promise<DesignGenerationResult>((_resolve, reject) => {
          generationSignal = signal;
          signal.addEventListener("abort", () => {
            reject(new DOMException("Generation aborted", "AbortError"));
          });
        }),
    );
    const { container, root } = await renderDesign(createHost({ generate }));
    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    const stop = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Stop",
    );
    if (stop === undefined) throw new Error("Stop control missing");
    await act(async () => stop.click());

    expect(generationSignal?.aborted).toBe(true);
    expect(container.textContent).toContain("Cancelled before the host returned a result.");
    await act(async () => root.unmount());
  });

  it("does not overwrite a stopped message when the host resolves afterward", async () => {
    let resolveGeneration: ((result: DesignGenerationResult) => void) | undefined;
    const generate = vi.fn(
      () =>
        new Promise<DesignGenerationResult>((resolve) => {
          resolveGeneration = resolve;
        }),
    );
    const { container, root } = await renderDesign(createHost({ generate }));
    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    const stop = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Stop",
    );
    if (stop === undefined || resolveGeneration === undefined) {
      throw new Error("Stop controls missing");
    }
    await act(async () => stop.click());
    await act(async () => {
      resolveGeneration?.(GENERATION_RESULT);
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(container.textContent).toContain("Stopped");
    expect(container.textContent).not.toContain("Generated result");
    await act(async () => root.unmount());
  });

  it("resends the adjacent user prompt for regenerate", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }));
    const regenerate = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Regenerate",
    );
    if (regenerate === undefined) throw new Error("Regenerate control missing");

    await act(async () => regenerate.click());

    expect(generate).toHaveBeenCalledWith(
      'Use the real stale count in the header.\n\nScope: Editing Index header (TSX); the user is pointing at the layer named "Index header".',
      expect.any(AbortSignal),
      { skills: expect.any(Array) },
    );
    await act(async () => root.unmount());
  });

  it("resends the adjacent user prompt for retry", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const assistantMessage = DOCUMENT.messages[1];
    if (assistantMessage?.role !== "assistant") throw new Error("Assistant fixture missing");
    const errorDocument: DesignDocument = {
      ...DOCUMENT,
      messages: [
        DOCUMENT.messages[0]!,
        {
          ...assistantMessage,
          role: "assistant",
          status: "error",
          title: "Generation failed",
          desc: "The previous attempt failed.",
        },
      ],
    };
    const { container, root } = await renderDesign(createHost({ generate }, errorDocument));
    const retry = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Retry",
    );
    if (retry === undefined) throw new Error("Retry control missing");

    await act(async () => retry.click());

    expect(generate).toHaveBeenCalledWith(
      'Use the real stale count in the header.\n\nScope: Editing Index header (TSX); the user is pointing at the layer named "Index header".',
      expect.any(AbortSignal),
      { skills: expect.any(Array) },
    );
    await act(async () => root.unmount());
  });

  it("restores a deleted layer through undo", async () => {
    const { container, root } = await renderDesign(
      createHost({ saveDocument: vi.fn(async () => {}) }),
    );
    const staleQueue = container.querySelector<HTMLButtonElement>(
      '[aria-label="Select Stale queue"]',
    );
    const deleteButton = container.querySelector<HTMLButtonElement>('[aria-label="Delete layer"]');
    if (staleQueue === null || deleteButton === null) throw new Error("Layer controls missing");

    await act(async () => staleQueue.click());
    await act(async () => deleteButton.click());
    expect(
      container.querySelector('.design-layer-select[aria-label="Select Stale queue"]'),
    ).toBeNull();

    const undo = container.querySelector<HTMLButtonElement>('[aria-label="Undo"]');
    if (undo === null) throw new Error("Undo control missing");
    await act(async () => undo.click());

    expect(
      container.querySelector('.design-layer-select[aria-label="Select Stale queue"]'),
    ).not.toBeNull();
    await act(async () => root.unmount());
  });

  it("restores a duplicated layer through undo", async () => {
    const { container, root } = await renderDesign(
      createHost({ saveDocument: vi.fn(async () => {}) }),
    );
    const duplicate = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Duplicate",
    );
    if (duplicate === undefined) throw new Error("Duplicate control missing");

    await act(async () => duplicate.click());
    expect(container.textContent).toContain("Index header copy");
    const undo = container.querySelector<HTMLButtonElement>('[aria-label="Undo"]');
    if (undo === null) throw new Error("Undo control missing");
    await act(async () => undo.click());

    expect(container.textContent).not.toContain("Index header copy");
    await act(async () => root.unmount());
  });

  it("renders layer geometry instead of the mock canvas-node geometry", async () => {
    const documentWithMovedLayer: DesignDocument = {
      ...DOCUMENT,
      layers: DOCUMENT.layers.map((layer) =>
        layer.id === "index-header"
          ? {
              ...layer,
              transform: { ...layer.transform, x: 123, y: 234, width: 345, height: 156 },
            }
          : layer,
      ),
    };
    const { container, root } = await renderDesign(createHost({}, documentWithMovedLayer));
    const node = container.querySelector<HTMLButtonElement>('[aria-label="Select Index header"]');
    if (node === null) throw new Error("Canvas layer missing");

    expect(node.style.left).toBe("123px");
    expect(node.style.top).toBe("234px");
    expect(node.style.width).toBe("345px");
    expect(node.style.height).toBe("156px");
    await act(async () => root.unmount());
  });

  it("selects the topmost layer at a canvas point and clears on empty canvas", async () => {
    const overlappingDocument: DesignDocument = {
      ...DOCUMENT,
      selectedLayerId: "index-header",
      layers: [
        {
          ...DOCUMENT.layers[0]!,
          transform: { x: 50, y: 50, width: 120, height: 120 },
        },
        {
          ...DOCUMENT.layers[1]!,
          transform: { x: 80, y: 80, width: 120, height: 120 },
        },
      ],
    };
    const { container, root } = await renderDesign(createHost({}, overlappingDocument));
    const stage = container.querySelector<HTMLDivElement>(".design-canvas-stage");
    if (stage === null) throw new Error("Canvas stage missing");

    await act(async () => {
      stage.dispatchEvent(new MouseEvent("click", { bubbles: true, clientX: 100, clientY: 100 }));
    });

    expect(
      container
        .querySelector<HTMLButtonElement>('[aria-label="Select Stale queue"]')
        ?.getAttribute("aria-pressed"),
    ).toBe("true");
    expect(
      container
        .querySelector<HTMLButtonElement>('[aria-label="Select Index header"]')
        ?.getAttribute("aria-pressed"),
    ).toBe("false");

    await act(async () => {
      stage.dispatchEvent(new MouseEvent("click", { bubbles: true, clientX: 900, clientY: 900 }));
    });

    expect(container.querySelector(".design-canvas-node-selected")).toBeNull();
    await act(async () => root.unmount());
  });

  it("composes drag movement with a pan change that happens mid-drag", async () => {
    const { container, root } = await renderDesign(createHost());
    const canvas = container.querySelector<HTMLDivElement>(".design-canvas");
    const stage = container.querySelector<HTMLDivElement>(".design-canvas-stage");
    if (canvas === null || stage === null) throw new Error("Canvas missing");

    await act(async () => {
      stage.dispatchEvent(
        pointerEvent("pointerdown", { button: 0, clientX: 100, clientY: 100, pointerId: 1 }),
      );
    });
    await act(async () => {
      stage.dispatchEvent(
        pointerEvent("pointermove", { clientX: 110, clientY: 100, pointerId: 1 }),
      );
    });
    await act(async () => {
      canvas.dispatchEvent(wheelEvent({ clientX: 100, clientY: 100, deltaMode: 0, deltaY: -8 }));
    });
    await act(async () => {
      stage.dispatchEvent(
        pointerEvent("pointermove", { clientX: 120, clientY: 100, pointerId: 1 }),
      );
    });

    const afterFirstMove = panViewport(createViewport(), { x: 10, y: 0 });
    const afterWheel = zoomViewport(afterFirstMove, { deltaY: -8, deltaMode: 0 }, 100, 100, 0);
    expect(stage.style.transform).toBe(viewportTransform(panViewport(afterWheel, { x: 10, y: 0 })));

    await act(async () => root.unmount());
  });

  it("selects the clicked layer when rendered content is outside the math hit", async () => {
    const overlappingDocument: DesignDocument = {
      ...DOCUMENT,
      selectedLayerId: "stale-queue",
      layers: [
        {
          ...DOCUMENT.layers[0]!,
          transform: { x: 50, y: 50, width: 120, height: 120 },
        },
        {
          ...DOCUMENT.layers[1]!,
          transform: { x: 80, y: 80, width: 120, height: 120 },
        },
      ],
    };
    const { container, root } = await renderDesign(createHost({}, overlappingDocument));
    const indexHeader = container.querySelector<HTMLButtonElement>(
      '[aria-label="Select Index header"]',
    );
    if (indexHeader === null) throw new Error("Canvas layer missing");

    await act(async () => {
      indexHeader.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    });

    expect(indexHeader.getAttribute("aria-pressed")).toBe("true");
    await act(async () => root.unmount());
  });

  it("does not suppress the next selection after a pointer is cancelled", async () => {
    const { container, root } = await renderDesign(createHost());
    const stage = container.querySelector<HTMLDivElement>(".design-canvas-stage");
    const staleQueue = container.querySelector<HTMLButtonElement>(
      '[aria-label="Select Stale queue"]',
    );
    if (stage === null || staleQueue === null) throw new Error("Canvas layer missing");

    await act(async () => {
      stage.dispatchEvent(
        pointerEvent("pointerdown", { button: 0, clientX: 10, clientY: 10, pointerId: 2 }),
      );
      stage.dispatchEvent(pointerEvent("pointermove", { clientX: 20, clientY: 20, pointerId: 2 }));
      stage.dispatchEvent(pointerEvent("pointercancel", { pointerId: 2 }));
      staleQueue.dispatchEvent(new MouseEvent("click", { bubbles: true }));
    });

    expect(staleQueue.getAttribute("aria-pressed")).toBe("true");
    await act(async () => root.unmount());
  });

  it("clamps the initial host zoom before rendering the state and canvas", async () => {
    const zoomDocument: DesignDocument = {
      ...DOCUMENT,
      initialState: { ...DOCUMENT.initialState, zoom: 5 },
    };
    const { container, root } = await renderDesign(createHost({}, zoomDocument));
    const zoomValue = container.querySelector<HTMLButtonElement>(".design-zoom-value");
    const stage = container.querySelector<HTMLDivElement>(".design-canvas-stage");
    if (zoomValue === null || stage === null) throw new Error("Zoom controls missing");

    expect(zoomValue.textContent).toBe("300%");
    expect(stage.style.transform).toContain("scale(3)");
    await act(async () => root.unmount());
  });

  it("includes the generated artifact when fitting the canvas", async () => {
    const generate = vi.fn(async () => ARTIFACT_RESULT);
    const { container, root } = await renderDesign(
      createHost({ generate }, { ...DOCUMENT, selectedLayerId: "" }),
    );
    await fillDraft(container, "Create the first pass.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    const canvas = container.querySelector<HTMLDivElement>(".design-canvas");
    const stage = container.querySelector<HTMLDivElement>(".design-canvas-stage");
    const fit = container.querySelector<HTMLButtonElement>(".design-fit-button");
    if (send === null || canvas === null || stage === null || fit === null) {
      throw new Error("Canvas controls missing");
    }
    await act(async () => send.click());

    Object.defineProperty(canvas, "getBoundingClientRect", {
      configurable: true,
      value: () => ({ width: 800, height: 600, left: 0, top: 0 }),
    });
    await act(async () => fit.click());

    const layerRects: NodeRect[] = DOCUMENT.layers.map((layer, index) => ({
      id: layer.id,
      x: layer.transform.x,
      y: layer.transform.y,
      w: layer.transform.width,
      h: layer.transform.height,
      z: index,
    }));
    const expected = fitViewport(
      nodesBounds([
        ...layerRects,
        {
          id: "generated-artifact",
          x: nodesBounds(layerRects)?.x ?? 60,
          y: (nodesBounds(layerRects)?.y ?? 46) + (nodesBounds(layerRects)?.h ?? 0) + 32,
          w: 700,
          h: 500,
          z: layerRects.length,
        },
      ]),
      800,
      600,
    );
    expect(stage.style.transform).toBe(viewportTransform(expected));
    await act(async () => root.unmount());
  });

  it("registers and removes a non-passive wheel listener", async () => {
    const addEventListener = vi.spyOn(HTMLDivElement.prototype, "addEventListener");
    const removeEventListener = vi.spyOn(HTMLDivElement.prototype, "removeEventListener");
    const { root } = await renderDesign(createHost());

    const wheelRegistration = addEventListener.mock.calls.find(
      ([type, , options]) => type === "wheel" && typeof options === "object",
    );
    expect(wheelRegistration?.[2]).toEqual({ passive: false });

    await act(async () => root.unmount());
    expect(removeEventListener.mock.calls.some(([type]) => type === "wheel")).toBe(true);
    addEventListener.mockRestore();
    removeEventListener.mockRestore();
  });

  it("omits generation affordances when the host cannot generate", async () => {
    const { container, root } = await renderDesign(createHost());

    expect(container.querySelector(".design-generate-button")).toBeNull();
    expect(container.querySelector('[aria-label="Run visual check"]')).toBeNull();
    expect(container.textContent).not.toContain("Regenerate");
    await act(async () => root.unmount());
  });

  it("shows the all-sections summary and sends the same resolved slugs", async () => {
    const skillIndex = builtInSkillIndex();
    const generate = vi
      .fn<NonNullable<DesignHost["generate"]>>()
      .mockResolvedValue(GENERATION_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }));
    const summary = container.querySelector<HTMLButtonElement>(
      '[aria-label="Configure design craft"]',
    );
    if (summary === null) throw new Error("Craft summary missing");

    expect(summary.textContent).toBe(`Craft: all ${skillIndex.length} sections`);
    await fillDraft(container, "Use every craft rule.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(generate.mock.calls[0]?.[2]).toEqual({
      skills: skillIndex.map((entry) => entry.slug),
    });
    await act(async () => root.unmount());
  });

  it("restores a stored manual selection and reflects its count", async () => {
    const skillIndex = builtInSkillIndex();
    const selected = skillIndex[0];
    const omitted = skillIndex[1];
    if (selected === undefined || omitted === undefined) throw new Error("Built-in skills missing");
    skillSettingsMocks.load.mockResolvedValueOnce({
      version: 1,
      mode: "manual",
      enabledSlugs: [selected.slug],
    });
    const { container, root } = await renderDesign(
      createHost({ generate: vi.fn(async () => GENERATION_RESULT) }),
    );
    const summary = container.querySelector<HTMLButtonElement>(
      '[aria-label="Configure design craft"]',
    );
    if (summary === null) throw new Error("Craft summary missing");
    expect(summary.textContent).toBe(`Craft: 1 of ${skillIndex.length}`);

    await act(async () => summary.click());
    const selectedCheckbox = container.querySelector<HTMLInputElement>(
      `input[aria-label="Apply ${selected.title}"]`,
    );
    const omittedCheckbox = container.querySelector<HTMLInputElement>(
      `input[aria-label="Apply ${omitted.title}"]`,
    );
    if (selectedCheckbox === null || omittedCheckbox === null) {
      throw new Error("Craft choices missing");
    }
    expect(selectedCheckbox.checked).toBe(true);
    expect(omittedCheckbox.checked).toBe(false);
    await act(async () => root.unmount());
  });

  it("changes the manual selection through the preference save path", async () => {
    const skillIndex = builtInSkillIndex();
    const selected = skillIndex[0];
    if (selected === undefined) throw new Error("Built-in skills missing");
    const { container, root } = await renderDesign(
      createHost({ generate: vi.fn(async () => GENERATION_RESULT) }),
    );
    const summary = container.querySelector<HTMLButtonElement>(
      '[aria-label="Configure design craft"]',
    );
    if (summary === null) throw new Error("Craft summary missing");
    await act(async () => summary.click());
    const manual = container.querySelector<HTMLInputElement>('input[type="radio"][value="manual"]');
    const checkbox = container.querySelector<HTMLInputElement>(
      `input[aria-label="Apply ${selected.title}"]`,
    );
    if (manual === null || checkbox === null) throw new Error("Craft choices missing");

    await act(async () => manual.click());
    await act(async () => checkbox.click());

    expect(skillSettingsMocks.save).toHaveBeenLastCalledWith({
      version: 1,
      mode: "manual",
      enabledSlugs: [selected.slug],
    });
    await act(async () => root.unmount());
  });

  it("sends only the manually selected section and shows the matching count", async () => {
    const skillIndex = builtInSkillIndex();
    const selected = skillIndex[0];
    if (selected === undefined) throw new Error("Built-in skills missing");
    const generate = vi
      .fn<NonNullable<DesignHost["generate"]>>()
      .mockResolvedValue(GENERATION_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }));
    const summary = container.querySelector<HTMLButtonElement>(
      '[aria-label="Configure design craft"]',
    );
    if (summary === null) throw new Error("Craft summary missing");
    await act(async () => summary.click());
    const manual = container.querySelector<HTMLInputElement>('input[type="radio"][value="manual"]');
    const checkbox = container.querySelector<HTMLInputElement>(
      `input[aria-label="Apply ${selected.title}"]`,
    );
    if (manual === null || checkbox === null) throw new Error("Craft choices missing");
    await act(async () => manual.click());
    await act(async () => checkbox.click());

    expect(summary.textContent).toBe(`Craft: 1 of ${skillIndex.length}`);
    await fillDraft(container, "Use the selected craft section.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(generate.mock.calls[0]?.[2]).toEqual({ skills: [selected.slug] });
    await act(async () => root.unmount());
  });

  // A class assertion proves a string is present and nothing about what renders.
  // It gates the wiring only; whether the row actually reads as locked was checked
  // by reading design.css and computing the contrast of --silence on
  // --surface-muted (5.37:1), not by measuring the running app.
  it("marks every option row locked in all mode and none of them in manual mode", async () => {
    const { container, root } = await renderDesign(
      createHost({ generate: vi.fn(async () => GENERATION_RESULT) }),
    );
    const summary = container.querySelector<HTMLButtonElement>(
      '[aria-label="Configure design craft"]',
    );
    if (summary === null) throw new Error("Craft summary missing");
    await act(async () => summary.click());

    const rows = () => [...container.querySelectorAll(".design-skill-option")];
    expect(rows()).toHaveLength(builtInSkillIndex().length);
    expect(rows().every((row) => row.classList.contains("design-skill-option-locked"))).toBe(true);

    const manual = container.querySelector<HTMLInputElement>('input[type="radio"][value="manual"]');
    if (manual === null) throw new Error("Craft mode choice missing");
    await act(async () => manual.click());

    expect(rows().some((row) => row.classList.contains("design-skill-option-locked"))).toBe(false);
    await act(async () => root.unmount());
  });

  it("manual mode with no checked sections sends an empty skill list", async () => {
    const generate = vi
      .fn<NonNullable<DesignHost["generate"]>>()
      .mockResolvedValue(GENERATION_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }));
    const summary = container.querySelector<HTMLButtonElement>(
      '[aria-label="Configure design craft"]',
    );
    if (summary === null) throw new Error("Craft summary missing");
    await act(async () => summary.click());
    const manual = container.querySelector<HTMLInputElement>('input[type="radio"][value="manual"]');
    if (manual === null) throw new Error("Manual mode missing");
    await act(async () => manual.click());

    await fillDraft(container, "Do not apply craft doctrine.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    expect(generate.mock.calls[0]?.[2]).toEqual({ skills: [] });
    await act(async () => root.unmount());
  });
});
