// @vitest-environment happy-dom

import { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useAppStore } from "../../store/appStore";
import {
  artifactNodeRect,
  DesignSurface,
  smallestSectionAt,
  type DesignDocument,
  type DesignHost,
} from "./DesignSurface";
import { clearCachedArtifactSections, setCachedArtifactSections } from "./artifactStructure";

const settingsMocks = vi.hoisted(() => ({
  load: vi.fn(),
  save: vi.fn(),
  loadProvider: vi.fn(),
  loadStoredProvider: vi.fn(),
  saveProvider: vi.fn(),
  loadWorkspace: vi.fn(),
  loadStoredWorkspace: vi.fn(),
  saveWorkspace: vi.fn(),
}));

const providerMocks = vi.hoisted(() => ({
  daemonStatus: vi.fn(),
  list: vi.fn(),
  projectsList: vi.fn(),
  workspacesList: vi.fn(),
}));

vi.mock("./designSettings", async () => {
  const actual = await vi.importActual<typeof import("./designSettings")>("./designSettings");
  return {
    ...actual,
    loadDesignSkillSelection: settingsMocks.load,
    saveDesignSkillSelection: settingsMocks.save,
    loadDesignProviderId: settingsMocks.loadProvider,
    loadStoredDesignProviderId: settingsMocks.loadStoredProvider,
    saveDesignProviderId: settingsMocks.saveProvider,
    loadDesignWorkspaceId: settingsMocks.loadWorkspace,
    loadStoredDesignWorkspaceId: settingsMocks.loadStoredWorkspace,
    saveDesignWorkspaceId: settingsMocks.saveWorkspace,
  };
});

vi.mock("./DesignHistoryList", () => ({
  DesignHistoryList: () => null,
}));

vi.mock("./designHistory", () => ({
  recordDesignHistoryEntry: vi.fn(async () => true),
}));

vi.mock("./designHistoryOpen", () => ({
  openDesignHistoryEntry: vi.fn(),
}));

vi.mock("../../lib/tauri", () => ({
  daemonStatus: providerMocks.daemonStatus,
  providersList: providerMocks.list,
  projectsList: providerMocks.projectsList,
  workspacesList: providerMocks.workspacesList,
  reasonFromCause: (cause: unknown) => (cause instanceof Error ? cause.message : String(cause)),
  createSessionStateChannel: vi.fn(),
  sessionCreate: vi.fn(),
  sessionsList: vi.fn(),
  sessionsUnwatch: vi.fn(),
  sessionsWatch: vi.fn(),
}));

(
  globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

const DOCUMENT: DesignDocument = {
  name: "",
  path: "",
  contextPrefix: "Editing",
  draftPlaceholder: "Describe the change…",
  noContextPlaceholder: "Describe what to generate…",
  tokenFooter: "Surface state only.",
  selectedLayerId: "",
  grounded: true,
  initialState: {
    zoom: 1,
    radius: 14,
    flat: false,
    saved: true,
    draft: "",
    hiddenLayerIds: [],
  },
  layers: [],
  radiusOptions: [
    { token: "none", value: 0 },
    { token: "md", value: 14 },
  ],
  messages: [],
  workingMessage: {
    title: "Generating…",
    desc: "Asking the agent.",
  },
};

const ARTIFACT_HTML =
  "<header><h1>Shop</h1></header><main><section><h2>Deals</h2></section></main>";

const ARTIFACT_SECTIONS = [
  {
    anchor: "body[1]/header[1]",
    tag: "header",
    name: "Shop",
    depth: 1,
    rect: { x: 0, y: 0, width: 1280, height: 120 },
  },
  {
    anchor: "body[1]/header[1]/h1[1]",
    tag: "h1",
    name: "Shop",
    depth: 2,
    rect: { x: 40, y: 20, width: 400, height: 60 },
  },
  {
    anchor: "body[1]/main[1]",
    tag: "main",
    name: "Deals",
    depth: 1,
    rect: { x: 0, y: 120, width: 1280, height: 600 },
  },
  {
    anchor: "body[1]/main[1]/section[1]",
    tag: "section",
    name: "Deals",
    depth: 2,
    rect: { x: 40, y: 160, width: 1200, height: 400 },
  },
  {
    anchor: "body[1]/main[1]/section[1]/h2[1]",
    tag: "h2",
    name: "Deals",
    depth: 3,
    rect: { x: 60, y: 180, width: 600, height: 40 },
  },
] as const;

const GENERATION_BASE = {
  sessionId: "session-sections",
  peerSessionId: null,
  createdAtMs: 1_000,
  prompt: "host echo",
  title: "Generated result",
  desc: "Generated by the host.",
  sources: [],
  nodeIds: [],
};

function createHost(overrides: Partial<DesignHost> = {}): DesignHost {
  return {
    loadDocument: vi.fn(async () => DOCUMENT),
    saveDocument: vi.fn(async () => undefined),
    ...overrides,
  };
}

async function renderDesign(host: DesignHost): Promise<{
  container: HTMLDivElement;
  root: ReturnType<typeof createRoot>;
}> {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root = createRoot(container);
  await act(async () => {
    root.render(<DesignSurface host={host} />);
    await Promise.resolve();
    await Promise.resolve();
  });
  return { container, root };
}

async function fillDraft(container: HTMLDivElement, prompt: string): Promise<void> {
  const draft = container.querySelector<HTMLTextAreaElement>(
    'textarea[aria-label="Describe a design change"]',
  );
  if (draft === null) throw new Error("Design composer missing");
  const setValue = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set;
  if (setValue === undefined) throw new Error("textarea value setter did not exist");
  await act(async () => {
    setValue.call(draft, prompt);
    draft.dispatchEvent(new Event("input", { bubbles: true }));
  });
}

async function generateArtifact(
  container: HTMLDivElement,
  generate: ReturnType<typeof vi.fn>,
  prompt: string,
): Promise<void> {
  setCachedArtifactSections(ARTIFACT_HTML, [...ARTIFACT_SECTIONS]);
  await fillDraft(container, prompt);
  const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
  if (send === null) throw new Error("Generate control missing");
  await act(async () => {
    send.click();
    await Promise.resolve();
    await Promise.resolve();
  });
  expect(generate).toHaveBeenCalled();
}

function layerRowByName(container: HTMLDivElement, name: string): HTMLButtonElement {
  const rows = Array.from(container.querySelectorAll<HTMLButtonElement>(".design-layer-select"));
  const row = rows.find((candidate) => candidate.textContent?.includes(name));
  if (row === undefined) throw new Error(`Layer row for ${name} missing`);
  return row;
}

async function fillNote(container: HTMLDivElement, text: string): Promise<void> {
  const field = container.querySelector<HTMLInputElement>(
    'input[aria-label="Note for the agent on this section"]',
  );
  if (field === null) throw new Error("Note field missing");
  const setValue = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")?.set;
  if (setValue === undefined) throw new Error("input value setter did not exist");
  await act(async () => {
    setValue.call(field, text);
    field.dispatchEvent(new Event("input", { bubbles: true }));
  });
  const add = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
    (button) => button.textContent === "Add",
  );
  if (add === undefined) throw new Error("Add-note control missing");
  await act(async () => {
    add.click();
    await Promise.resolve();
  });
}

beforeEach(() => {
  useAppStore.setState({ plugins: null, installing: null, installError: null });
  settingsMocks.load.mockResolvedValue({ version: 1, mode: "all", enabledSlugs: [] });
  settingsMocks.save.mockResolvedValue(true);
  settingsMocks.loadProvider.mockResolvedValue(null);
  settingsMocks.loadStoredProvider.mockResolvedValue(null);
  settingsMocks.saveProvider.mockResolvedValue(true);
  settingsMocks.loadWorkspace.mockResolvedValue(null);
  settingsMocks.loadStoredWorkspace.mockResolvedValue(null);
  settingsMocks.saveWorkspace.mockResolvedValue(true);
  providerMocks.list.mockResolvedValue({ providers: [], unreadableDirs: 0 });
  providerMocks.daemonStatus.mockResolvedValue({ capabilities: [] });
  providerMocks.projectsList.mockResolvedValue([]);
  providerMocks.workspacesList.mockResolvedValue([]);
});

afterEach(() => {
  document.body.replaceChildren();
  clearCachedArtifactSections();
});

describe("artifactNodeRect with section layers", () => {
  it("ignores section layers so the frame never depends on its own sections", () => {
    const canvasLayer = {
      id: "panel",
      name: "Panel",
      kind: "TSX" as const,
      transform: { x: 60, y: 46, width: 300, height: 124 },
    };
    const sectionLayer = {
      id: "section:body[1]/main[1]",
      name: "Deals",
      kind: "SECTION" as const,
      transform: { x: 60, y: 166, width: 1280, height: 600 },
      section: { tag: "main", anchor: "body[1]/main[1]" },
    };
    expect(artifactNodeRect([canvasLayer, sectionLayer], 800)).toEqual(
      artifactNodeRect([canvasLayer], 800),
    );
    expect(artifactNodeRect([], 800)).toMatchObject({ x: 60, y: 46, w: 1280, h: 800 });
  });
});

describe("smallestSectionAt", () => {
  const outer = {
    id: "section:outer",
    name: "Outer",
    kind: "SECTION" as const,
    transform: { x: 0, y: 0, width: 100, height: 100 },
  };
  const inner = {
    id: "section:inner",
    name: "Inner",
    kind: "SECTION" as const,
    transform: { x: 10, y: 10, width: 20, height: 20 },
  };

  it("picks the smallest containing rect when sections nest", () => {
    // Nested or not, document order must not matter: the deepest wins.
    expect(smallestSectionAt([outer, inner], [], { x: 15, y: 15 })?.id).toBe("section:inner");
    expect(smallestSectionAt([inner, outer], [], { x: 15, y: 15 })?.id).toBe("section:inner");
    expect(smallestSectionAt([outer, inner], [], { x: 50, y: 50 })?.id).toBe("section:outer");
  });

  it("returns null outside every section and skips hidden ones", () => {
    expect(smallestSectionAt([outer, inner], [], { x: 500, y: 500 })).toBeNull();
    expect(smallestSectionAt([outer, inner], ["section:inner"], { x: 15, y: 15 })?.id).toBe(
      "section:outer",
    );
  });
});

describe("DesignSurface direct-on-canvas section selection", () => {
  it("paints one transparent overlay per section, smallest on top", async () => {
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate });
    const { container, root } = await renderDesign(host);
    await generateArtifact(container, generate, "Build a shop page.");

    const overlays = container.querySelectorAll<HTMLButtonElement>(
      ".design-canvas-section-overlay",
    );
    expect(overlays).toHaveLength(5);
    // Largest-first paint order: the smallest (deepest) overlay is on top and
    // receives the pointer, matching smallestSectionAt.
    const areas = Array.from(overlays).map((overlay) => {
      const width = Number.parseFloat(overlay.style.width);
      const height = Number.parseFloat(overlay.style.height);
      return width * height;
    });
    expect(areas).toEqual([...areas].sort((left, right) => right - left));
    // The display iframe itself stays out of the pointer path.
    const frame = container.querySelector<HTMLElement>(".design-artifact-frame");
    expect(frame?.style.pointerEvents).toBe("none");
    await act(async () => root.unmount());
  });

  it("selects from the canvas into the same state as the panel", async () => {
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate });
    const { container, root } = await renderDesign(host);
    await generateArtifact(container, generate, "Build a shop page.");

    // Last overlay is the smallest: the h2 (600 × 40) inside the section.
    const overlays = container.querySelectorAll<HTMLButtonElement>(
      ".design-canvas-section-overlay",
    );
    const target = overlays[overlays.length - 1];
    if (target === undefined) throw new Error("Section overlays missing");
    await act(async () => {
      target.click();
      await Promise.resolve();
    });

    const inspector = container.querySelector(".design-inspector-panel");
    if (inspector === null) throw new Error("Section inspector missing after overlay click");
    expect(inspector.textContent).toContain("body[1]/main[1]/section[1]/h2[1]");
    // One state, not two: the panel row for the same section marks selected.
    const selectedRows = container.querySelectorAll(".design-layer-row-selected");
    expect(selectedRows).toHaveLength(1);
    const highlight = container.querySelector<HTMLElement>(".design-canvas-section-highlight");
    if (highlight === null) throw new Error("Section highlight missing");
    expect(highlight.style.width).toBe("600px");
    expect(highlight.style.height).toBe("40px");
    await act(async () => root.unmount());
  });

  it("highlights on hover without selecting", async () => {
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate });
    const { container, root } = await renderDesign(host);
    await generateArtifact(container, generate, "Build a shop page.");

    const overlays = container.querySelectorAll<HTMLButtonElement>(
      ".design-canvas-section-overlay",
    );
    const target = overlays[overlays.length - 1];
    if (target === undefined) throw new Error("Section overlays missing");
    await act(async () => {
      target.dispatchEvent(new MouseEvent("mouseover", { bubbles: true }));
      await Promise.resolve();
    });

    const hover = container.querySelector<HTMLElement>(".design-canvas-section-hover");
    if (hover === null) throw new Error("Section hover highlight missing");
    expect(hover.style.width).toBe("600px");
    // Hover alone selects nothing: no inspector, no marked row.
    expect(container.querySelector(".design-inspector-panel")).toBeNull();
    expect(container.querySelector(".design-layer-row-selected")).toBeNull();

    await act(async () => {
      target.dispatchEvent(new MouseEvent("mouseout", { bubbles: true }));
      await Promise.resolve();
    });
    expect(container.querySelector(".design-canvas-section-hover")).toBeNull();
    await act(async () => root.unmount());
  });
});

describe("DesignSurface page sections", () => {
  it("lists measured page sections in the Layers panel", async () => {
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate });
    const { container, root } = await renderDesign(host);
    expect(container.querySelector(".design-layers-panel")).toBeNull();

    await generateArtifact(container, generate, "Build a shop page.");

    const panel = container.querySelector(".design-layers-panel");
    if (panel === null) throw new Error("Layers panel missing after measurement");
    const kinds = Array.from(panel.querySelectorAll(".design-layer-kind")).map(
      (badge) => badge.textContent,
    );
    // The badge carries the measured tag (nav, h2, section), not the repeated kind.
    expect(kinds).toEqual(["header", "h1", "main", "section", "h2"]);
    expect(panel.textContent).toContain("Deals");
    await act(async () => root.unmount());
  });

  it("selects a section into a section inspector with a canvas highlight", async () => {
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate });
    const { container, root } = await renderDesign(host);
    await generateArtifact(container, generate, "Build a shop page.");

    await act(async () => {
      layerRowByName(container, "Deals").click();
      await Promise.resolve();
    });

    const inspector = container.querySelector(".design-inspector-panel");
    if (inspector === null) throw new Error("Section inspector missing");
    expect(inspector.textContent).toContain("<main>");
    expect(inspector.textContent).toContain("body[1]/main[1]");
    expect(inspector.textContent).toContain("1280 × 600 px");
    // Canvas-node controls are meaningless for a measured section.
    expect(inspector.querySelector(".design-radius-option")).toBeNull();
    expect(inspector.textContent).not.toContain("Corners");
    expect(inspector.textContent).not.toContain("Elevation");
    expect(inspector.textContent).not.toContain("Duplicate");
    expect(inspector.textContent).not.toContain("Delete");

    // World highlight: artifact origin (60, 46) plus the measured page rect.
    const highlight = container.querySelector<HTMLElement>(".design-canvas-section-highlight");
    if (highlight === null) throw new Error("Section highlight missing");
    expect(highlight.style.left).toBe("60px");
    expect(highlight.style.top).toBe("166px");
    expect(highlight.style.width).toBe("1280px");
    expect(highlight.style.height).toBe("600px");
    await act(async () => root.unmount());
  });

  it("selects the section under a canvas click instead of the whole artifact", async () => {
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate });
    const { container, root } = await renderDesign(host);
    await generateArtifact(container, generate, "Build a shop page.");

    const canvas = container.querySelector(".design-canvas");
    if (canvas === null) throw new Error("Canvas missing");
    // World (500, 180): inside main (y 166–766) but above its section (y 206+).
    // The fitted viewport (zoom/pan) maps world to client; invert it here so
    // the click lands on the section whatever the fit produced.
    const stage = container.querySelector<HTMLElement>(".design-canvas-stage");
    const transform = stage?.style.transform ?? "";
    const match = /translate\((-?[\d.]+)px, (-?[\d.]+)px\) scale\(([\d.]+)\)/.exec(transform);
    if (match === null) throw new Error(`Stage transform missing: ${transform}`);
    const [, panX, panY, zoom] = match.map(Number);
    const clientX = 500 * (zoom ?? 1) + (panX ?? 0);
    const clientY = 180 * (zoom ?? 1) + (panY ?? 0);
    await act(async () => {
      canvas.dispatchEvent(new MouseEvent("click", { bubbles: true, clientX, clientY }));
      await Promise.resolve();
    });

    const inspector = container.querySelector(".design-inspector-panel");
    if (inspector === null) throw new Error("Section inspector missing after canvas click");
    expect(inspector.textContent).toContain("body[1]/main[1]");
    await act(async () => root.unmount());
  });

  it("sends a section note to the agent in the scope block", async () => {
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate });
    const { container, root } = await renderDesign(host);
    await generateArtifact(container, generate, "Build a shop page.");

    await act(async () => {
      layerRowByName(container, "Deals").click();
      await Promise.resolve();
    });
    await fillNote(container, "Make the CTA louder.");

    // Marked on the canvas without selecting, dotted in the panel.
    expect(container.querySelector(".design-canvas-note-mark")).not.toBeNull();
    const mainRow = layerRowByName(container, "Deals").closest(".design-layer-row");
    expect(mainRow?.querySelector(".design-layer-note-dot")).not.toBeNull();

    await fillDraft(container, "Refine the deals.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => {
      send.click();
      await Promise.resolve();
      await Promise.resolve();
    });

    expect(generate).toHaveBeenLastCalledWith(
      expect.stringContaining("Section notes:\n- [body[1]/main[1]]: Make the CTA louder."),
      expect.any(AbortSignal),
      expect.anything(),
    );
    await act(async () => root.unmount());
  });

  it("shows orphaned notes instead of losing them, flagged in the next prompt", async () => {
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate });
    const { container, root } = await renderDesign(host);
    await generateArtifact(container, generate, "Build a shop page.");

    await act(async () => {
      useAppStore
        .getState()
        .setSectionNotes(host, [{ anchor: "body[1]/main[1]/section[9]", text: "Keep me" }]);
      await Promise.resolve();
    });

    const orphanBadge = container.querySelector(".design-layer-orphan-badge");
    if (orphanBadge === null) throw new Error("Orphan badge missing");
    expect(orphanBadge.textContent).toBe("orphan");
    expect(container.querySelector(".design-layer-orphans")?.textContent).toContain(
      "body[1]/main[1]/section[9]",
    );

    await act(async () => {
      layerRowByName(container, "Deals").click();
      await Promise.resolve();
    });
    await fillDraft(container, "Refine again.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => {
      send.click();
      await Promise.resolve();
      await Promise.resolve();
    });
    expect(generate).toHaveBeenLastCalledWith(
      expect.stringContaining(
        "[body[1]/main[1]/section[9]] (anchor not found in the current page): Keep me",
      ),
      expect.any(AbortSignal),
      expect.anything(),
    );
    await act(async () => root.unmount());
  });

  it("saves section notes with the document", async () => {
    const saveDocument = vi.fn(async () => undefined);
    const generate = vi.fn(async () => ({ ...GENERATION_BASE, artifactHtml: ARTIFACT_HTML }));
    const host = createHost({ generate, saveDocument });
    const { container, root } = await renderDesign(host);
    await generateArtifact(container, generate, "Build a shop page.");

    await act(async () => {
      useAppStore
        .getState()
        .setSectionNotes(host, [{ anchor: "body[1]/main[1]", text: "Persist me" }]);
      await Promise.resolve();
    });

    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (save === null) throw new Error("Save control missing");
    await act(async () => {
      save.click();
      await Promise.resolve();
      await Promise.resolve();
    });
    expect(saveDocument).toHaveBeenCalledWith(
      expect.objectContaining({
        sectionNotes: [{ anchor: "body[1]/main[1]", text: "Persist me" }],
      }),
    );
    await act(async () => root.unmount());
  });
});
