// @vitest-environment happy-dom

import { act } from "react";
import { createRoot } from "react-dom/client";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useAppStore } from "../../store/appStore";
import { DesignSurface, type DesignDocument, type DesignHost } from "./DesignSurface";
import type { DesignGenerationResult } from "./designHost";

(
  globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

const DOCUMENT: DesignDocument = {
  name: "Index browser",
  path: "~/dev/devboule/src/design",
  provider: "Claude Code · High",
  contextPrefix: "Editing",
  draftPlaceholder: "Describe the change to Index header…",
  noContextPlaceholder: "Describe what to generate…",
  generationFooter: "Generations land on the Design canvas.",
  tokenFooter: "Values snap to design tokens (DTCG)",
  initialState: {
    tool: "move",
    zoom: 1,
    radius: 14,
    flat: false,
    saved: false,
    grounded: true,
    draft: "",
    selectedLayerId: "index-header",
    hiddenLayerIds: [],
  },
  layers: [
    {
      id: "index-header",
      name: "Index header",
      kind: "TSX",
      transform: { x: 396, y: 92, width: 336, height: 198, hug: true },
    },
    {
      id: "stale-queue",
      name: "Stale queue",
      kind: "TSX",
      transform: { x: 60, y: 46, width: 300, height: 124 },
    },
  ],
  canvasNodes: [
    {
      id: "index-header",
      variant: "index-header",
      name: "Index header",
      x: 396,
      y: 92,
      width: 336,
      height: 198,
    },
    {
      id: "stale-queue",
      variant: "stale-queue",
      name: "Stale queue",
      x: 60,
      y: 46,
      width: 300,
      height: 124,
    },
  ],
  canvasContent: {
    staleQueue: { label: "Stale queue", rowWidths: [100, 82, 68] },
    indexHeader: {
      label: "Index header",
      staleBadge: "37 stale",
      cardCount: 3,
      selectedCardIndex: 2,
      primaryAction: "Reindex",
      secondaryAction: "Export",
    },
    aiRegion: { x: 420, y: 300, width: 240, height: 96, actionLabel: "Analyze this region" },
  },
  radiusOptions: [
    { token: "none", value: 0 },
    { token: "sm", value: 8 },
    { token: "md", value: 14 },
    { token: "lg", value: 22 },
  ],
  messages: [
    {
      id: 0,
      role: "user",
      text: "Use the real stale count in the header.",
    },
    {
      id: 1,
      role: "assistant",
      status: "done",
      title: "Edited Index header",
      desc: "Applied the edit.",
      sources: [],
      nodeIds: ["index-header"],
    },
  ],
  workingMessage: {
    title: "Generating…",
    desc: "Reading the grounded files, then writing the node.",
  },
};

const GENERATION_RESULT = {
  prompt: "host echo",
  title: "Generated result",
  desc: "Generated by the host.",
  sources: ["host.ts"],
  nodeIds: ["index-header"],
};

function createHost(
  overrides: Partial<DesignHost> = {},
  document: DesignDocument = DOCUMENT,
): DesignHost {
  return {
    loadDocument: vi.fn(async () => document),
    ...overrides,
  };
}

async function fillDraft(container: HTMLDivElement, prompt: string): Promise<HTMLTextAreaElement> {
  const draft = container.querySelector<HTMLTextAreaElement>(
    'textarea[aria-label="Describe a design change"]',
  );
  if (draft === null) throw new Error("Design composer missing");
  const setValue = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, "value")?.set;
  if (setValue === undefined) throw new Error("textarea value setter did not exist");

  await act(async () => {
    setValue.call(draft, prompt);
    draft.dispatchEvent(new Event("input", { bubbles: true }));
  });
  return draft;
}

async function renderDesign(host: DesignHost): Promise<{
  container: HTMLDivElement;
  root: ReturnType<typeof createRoot>;
}> {
  const container = document.createElement("div");
  document.body.appendChild(container);
  const root = createRoot(container);
  await act(async () => {
    root.render(<DesignSurface host={host} />);
  });
  return { container, root };
}

beforeEach(() => {
  useAppStore.setState({ plugins: null, installing: null, installError: null });
});

afterEach(() => {
  document.body.replaceChildren();
});

describe("DesignSurface host capabilities", () => {
  it("omits the save control when the host is view-only", async () => {
    const { container, root } = await renderDesign(createHost());

    expect(container.querySelector(".design-save-primary")).toBeNull();
    expect(container.querySelector(".design-save-menu")).toBeNull();
    await act(async () => root.unmount());
  });

  it("calls the host exactly once with the loaded document when saving", async () => {
    const saveDocument = vi.fn(async (_document: DesignDocument) => undefined);
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (save === null) throw new Error("Save control missing");

    await act(async () => save.click());

    expect(saveDocument).toHaveBeenCalledTimes(1);
    expect(saveDocument).toHaveBeenCalledWith(DOCUMENT);
    await act(async () => root.unmount());
  });

  it("saves the current on-screen snapshot rather than the loaded snapshot", async () => {
    const saveDocument = vi.fn(async (_document: DesignDocument) => undefined);
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const radius = container.querySelector<HTMLButtonElement>(
      '[aria-label="Set radius.sm, 8 pixels"]',
    );
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (radius === null || save === null) throw new Error("Save controls missing");

    await act(async () => radius.click());
    await act(async () => save.click());

    const savedDocument = saveDocument.mock.calls[0]?.[0];
    expect(savedDocument?.initialState.radius).toBe(8);
    await act(async () => root.unmount());
  });

  it("keeps the document dirty when an edit lands during a save", async () => {
    let resolveSave: (() => void) | undefined;
    const saveDocument = vi.fn(
      () =>
        new Promise<void>((resolve) => {
          resolveSave = resolve;
        }),
    );
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const radius = container.querySelector<HTMLButtonElement>(
      '[aria-label="Set radius.sm, 8 pixels"]',
    );
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (radius === null || save === null) throw new Error("Save controls missing");

    await act(async () => radius.click());
    await act(async () => save.click());
    const undo = container.querySelector<HTMLButtonElement>('[aria-label="Undo"]');
    if (undo === null || resolveSave === undefined) throw new Error("Save race controls missing");

    await act(async () => undo.click());
    await act(async () => {
      resolveSave?.();
      await Promise.resolve();
    });

    expect(container.querySelector(".design-save-status")?.textContent).toContain(
      "Unsaved changes",
    );
    await act(async () => root.unmount());
  });

  it("surfaces save failures without claiming that the document was saved", async () => {
    const saveDocument = vi.fn(async () => {
      throw new Error("Repository unavailable");
    });
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (save === null) throw new Error("Save control missing");

    await act(async () => save.click());

    expect(container.querySelector('[role="alert"]')?.textContent).toContain(
      "Repository unavailable",
    );
    expect(container.querySelector(".design-save-status")?.textContent).not.toContain("Saved");
    await act(async () => root.unmount());
  });

  it("clears an earlier save error after a later save succeeds", async () => {
    const saveDocument = vi
      .fn<NonNullable<DesignHost["saveDocument"]>>()
      .mockRejectedValueOnce(new Error("Repository unavailable"))
      .mockResolvedValueOnce(undefined);
    const { container, root } = await renderDesign(createHost({ saveDocument }));
    const save = container.querySelector<HTMLButtonElement>(".design-save-primary");
    if (save === null) throw new Error("Save control missing");

    await act(async () => save.click());
    expect(container.querySelector('[role="alert"]')?.textContent).toContain(
      "Repository unavailable",
    );
    await act(async () => save.click());

    expect(container.querySelector('[role="alert"]')).toBeNull();
    expect(container.querySelector(".design-save-status")?.textContent).toContain("Saved");
    await act(async () => root.unmount());
  });

  it("shows a load failure instead of rendering an empty document", async () => {
    const host = createHost({
      loadDocument: vi.fn(async () => {
        throw new Error("Document unavailable");
      }),
    });
    const { container, root } = await renderDesign(host);

    expect(container.querySelector('[role="alert"]')?.textContent).toContain(
      "Document unavailable",
    );
    expect(container.querySelector(".design-toolbar")).toBeNull();
    await act(async () => root.unmount());
  });

  it("shows a generation failure in the assistant", async () => {
    const generate = vi.fn(async () => {
      throw new Error("Generation unavailable");
    });
    const { container, root } = await renderDesign(createHost({ generate }));
    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");

    await act(async () => send.click());

    expect(generate).toHaveBeenCalledTimes(1);
    expect(container.textContent).toContain("Generation failed");
    expect(container.textContent).toContain("Generation unavailable");
    await act(async () => root.unmount());
  });

  it("applies a generation result as soon as the host resolves", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }));
    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");

    await act(async () => send.click());

    expect(container.textContent).toContain("Generated result");
    expect(container.textContent).not.toContain("Generating…");
    await act(async () => root.unmount());
  });

  it("aborts a pending generation and reports an actual cancellation", async () => {
    let generationSignal: AbortSignal | undefined;
    const generate = vi.fn(
      (_prompt: string, signal: AbortSignal) =>
        new Promise<DesignGenerationResult>((_resolve, reject) => {
          generationSignal = signal;
          signal.addEventListener("abort", () => {
            reject(new DOMException("Generation aborted", "AbortError"));
          });
        }),
    );
    const { container, root } = await renderDesign(createHost({ generate }));
    await fillDraft(container, "Make the stale count dynamic.");
    const send = container.querySelector<HTMLButtonElement>(".design-generate-button");
    if (send === null) throw new Error("Generate control missing");
    await act(async () => send.click());

    const stop = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Stop",
    );
    if (stop === undefined) throw new Error("Stop control missing");
    await act(async () => stop.click());

    expect(generationSignal?.aborted).toBe(true);
    expect(container.textContent).toContain("Cancelled before the host returned a result.");
    await act(async () => root.unmount());
  });

  it("resends the adjacent user prompt for regenerate", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const { container, root } = await renderDesign(createHost({ generate }));
    const regenerate = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Regenerate",
    );
    if (regenerate === undefined) throw new Error("Regenerate control missing");

    await act(async () => regenerate.click());

    expect(generate).toHaveBeenCalledWith(
      "Use the real stale count in the header.",
      expect.any(AbortSignal),
    );
    await act(async () => root.unmount());
  });

  it("resends the adjacent user prompt for retry", async () => {
    const generate = vi.fn(async () => GENERATION_RESULT);
    const assistantMessage = DOCUMENT.messages[1];
    if (assistantMessage?.role !== "assistant") throw new Error("Assistant fixture missing");
    const errorDocument: DesignDocument = {
      ...DOCUMENT,
      messages: [
        DOCUMENT.messages[0]!,
        {
          ...assistantMessage,
          role: "assistant",
          status: "error",
          title: "Generation failed",
          desc: "The previous attempt failed.",
        },
      ],
    };
    const { container, root } = await renderDesign(createHost({ generate }, errorDocument));
    const retry = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Retry",
    );
    if (retry === undefined) throw new Error("Retry control missing");

    await act(async () => retry.click());

    expect(generate).toHaveBeenCalledWith(
      "Use the real stale count in the header.",
      expect.any(AbortSignal),
    );
    await act(async () => root.unmount());
  });

  it("restores a deleted layer through undo", async () => {
    const { container, root } = await renderDesign(
      createHost({ saveDocument: vi.fn(async () => {}) }),
    );
    const staleQueue = container.querySelector<HTMLButtonElement>(
      '[aria-label="Select Stale queue"]',
    );
    const deleteButton = container.querySelector<HTMLButtonElement>('[aria-label="Delete layer"]');
    if (staleQueue === null || deleteButton === null) throw new Error("Layer controls missing");

    await act(async () => staleQueue.click());
    await act(async () => deleteButton.click());
    expect(
      container.querySelector('.design-layer-select[aria-label="Select Stale queue"]'),
    ).toBeNull();

    const undo = container.querySelector<HTMLButtonElement>('[aria-label="Undo"]');
    if (undo === null) throw new Error("Undo control missing");
    await act(async () => undo.click());

    expect(
      container.querySelector('.design-layer-select[aria-label="Select Stale queue"]'),
    ).not.toBeNull();
    await act(async () => root.unmount());
  });

  it("restores a duplicated layer through undo", async () => {
    const { container, root } = await renderDesign(
      createHost({ saveDocument: vi.fn(async () => {}) }),
    );
    const duplicate = Array.from(container.querySelectorAll<HTMLButtonElement>("button")).find(
      (button) => button.textContent === "Duplicate",
    );
    if (duplicate === undefined) throw new Error("Duplicate control missing");

    await act(async () => duplicate.click());
    expect(container.textContent).toContain("Index header copy");
    const undo = container.querySelector<HTMLButtonElement>('[aria-label="Undo"]');
    if (undo === null) throw new Error("Undo control missing");
    await act(async () => undo.click());

    expect(container.textContent).not.toContain("Index header copy");
    await act(async () => root.unmount());
  });

  it("omits generation affordances when the host cannot generate", async () => {
    const { container, root } = await renderDesign(createHost());

    expect(container.querySelector(".design-generate-button")).toBeNull();
    expect(container.querySelector('[aria-label="Run visual check"]')).toBeNull();
    expect(container.textContent).not.toContain("Regenerate");
    await act(async () => root.unmount());
  });
});
