// The release flow against a throwaway repository: every preflight rejection
// and one real commit/tag, with cargo stubbed through the runner seam so no
// test can reach the real lockfile. The fixture lives under os.tmpdir() and
// is removed after each test; the real repository is never touched.

import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { runCheckTag, runRelease } from "./release.mjs";

// Directory in the fixture repo → package name. src-tauri comes first and
// carries a dependency table with its own `version =` line *before*
// [package], so a writer that is not [package]-scoped rewrites the wrong
// field and these tests fail.
const CRATES = [
  ["src-tauri", "devboule"],
  ["crates/devboule-augur", "devboule-augur"],
  ["crates/devboule-daemon", "devboule-daemon"],
  ["crates/devboule-plugin-rpc", "devboule-plugin-rpc"],
  ["crates/devboule-protocol", "devboule-protocol"],
  ["crates/oracle-core", "oracle-core"],
  ["crates/polis-backend", "polis-backend"],
];
const RELEASE_PATHS = [
  "src-tauri/tauri.conf.json",
  "package.json",
  ...CRATES.map(([directory]) => `${directory}/Cargo.toml`),
  "Cargo.lock",
  "CHANGELOG.md",
];
const REVIEWED_NOTES = [
  "## [0.1.1] - 2026-10-07",
  "",
  "### Changes",
  "- Fixture release (deadbee)",
  "",
].join("\n");

function git(root, args) {
  return execFileSync("git", args, { cwd: root, encoding: "utf8" });
}

function writeFixture(root) {
  mkdirSync(join(root, "src-tauri"), { recursive: true });
  writeFileSync(
    join(root, "package.json"),
    `${JSON.stringify({ name: "release-fixture", version: "0.1.0", private: true }, null, 2)}\n`,
  );
  writeFileSync(
    join(root, "src-tauri", "tauri.conf.json"),
    [
      "{",
      '  "$schema": "https://schema.tauri.app/config/2",',
      "  // Tauri reads the shipped version from this line.",
      '  "version": "0.1.0",',
      '  "identifier": "com.example.fixture"',
      "}",
      "",
    ].join("\n"),
  );
  writeFileSync(
    join(root, "Cargo.toml"),
    [
      "[workspace]",
      "resolver = '2'",
      "members = [",
      ...CRATES.map(([dir]) => `    "${dir}",`),
      "]",
      "",
    ].join("\n"),
  );
  for (const [directory, name] of CRATES) {
    mkdirSync(join(root, directory), { recursive: true });
    const packageTable =
      directory === "src-tauri"
        ? ["[dependencies.some-dep-table]", 'version = "1.0.0"', "", "[package]"].join("\n")
        : "[package]";
    writeFileSync(
      join(root, directory, "Cargo.toml"),
      `${packageTable}\nname = "${name}"\nversion = "0.1.0"\nedition = "2021"\n`,
    );
  }
  writeFileSync(
    join(root, "Cargo.lock"),
    [
      "# This file is automatically @generated by Cargo.",
      "version = 4",
      "",
      ...CRATES.flatMap(([, name]) => [`[[package]]`, `name = "${name}"`, `version = "0.1.0"`, ""]),
    ].join("\n"),
  );
  writeFileSync(join(root, "CHANGELOG.md"), "# Changelog\n\n## [Unreleased]\n");
}

function initFixture(root, origin) {
  writeFixture(root);
  git(root, ["init", "-q", "-b", "main"]);
  git(root, ["config", "user.name", "fixture"]);
  git(root, ["config", "user.email", "fixture@example.invalid"]);
  git(root, ["config", "core.autocrlf", "false"]);
  git(root, ["config", "commit.gpgsign", "false"]);
  git(root, ["add", "-A"]);
  git(root, ["commit", "-q", "-m", "Fixture baseline"]);
  execFileSync("git", ["init", "-q", "--bare", origin]);
  git(root, ["remote", "add", "origin", origin]);
  git(root, ["push", "-q", "-u", "origin", "main"]);
}

// Stand-in for `cargo update --workspace --offline`: rewrite the fixture
// lockfile's package versions to what package.json now says. Real cargo is
// never spawned, so no test can wait on the cargo slot or touch a lockfile
// outside the fixture.
function fixtureRunner(file, args, options) {
  if (file !== "cargo") {
    return execFileSync(file, args, options);
  }
  const next = JSON.parse(readFileSync(join(options.cwd, "package.json"), "utf8")).version;
  const lockPath = join(options.cwd, "Cargo.lock");
  const lock = readFileSync(lockPath, "utf8");
  writeFileSync(lockPath, lock.replaceAll(`version = "0.1.0"`, `version = "${next}"`));
  return "";
}

describe("release flow in a throwaway repository", () => {
  let root;
  let origin;
  let notesPath;

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), "release-flow-"));
    origin = `${root}-origin.git`;
    notesPath = `${root}-notes.md`;
    writeFileSync(notesPath, REVIEWED_NOTES);
    process.env.RELEASE_NOTES_FILE = notesPath;
    initFixture(root, origin);
  });

  afterEach(() => {
    delete process.env.RELEASE_NOTES_FILE;
    vi.restoreAllMocks();
    rmSync(root, { recursive: true, force: true });
    rmSync(origin, { recursive: true, force: true });
    rmSync(notesPath, { force: true });
  });

  const release = () => runRelease("patch", { root, runner: fixtureRunner });

  it("refuses a branch that is not main", () => {
    git(root, ["checkout", "-q", "-b", "feat/x"]);
    expect(release).toThrow(/only runs on main/);
  });

  it("refuses a dirty working tree", () => {
    const manifest = join(root, "src-tauri", "Cargo.toml");
    writeFileSync(manifest, `${readFileSync(manifest, "utf8")}\n`);
    expect(release).toThrow(/not clean/);
  });

  it("refuses a HEAD that origin/main does not have", () => {
    writeFileSync(join(root, "local-only.txt"), "local\n");
    git(root, ["add", "local-only.txt"]);
    git(root, ["commit", "-q", "-m", "Local commit never pushed"]);
    expect(release).toThrow(/is not origin\/main/);
  });

  it("refuses version drift", () => {
    const pkg = join(root, "package.json");
    writeFileSync(
      pkg,
      readFileSync(pkg, "utf8").replace('"version": "0.1.0"', '"version": "0.9.0"'),
    );
    git(root, ["add", "package.json"]);
    git(root, ["commit", "-q", "-m", "Drift the package version"]);
    git(root, ["push", "-q", "origin", "main"]);
    expect(release).toThrow(/version drift/);
  });

  it("refuses a release version whose tag already exists", () => {
    git(root, ["tag", "v0.1.1"]);
    expect(release).toThrow(/already exists/);
  });

  it("check-tag passes when the whole version inventory matches the tag", () => {
    writeFileSync(
      join(root, "CHANGELOG.md"),
      [
        "# Changelog",
        "",
        "## [Unreleased]",
        "",
        "## [0.1.0] - 2026-10-07",
        "",
        "### Changes",
        "- Fixture baseline (deadbee)",
        "",
      ].join("\n"),
    );
    expect(() => runCheckTag("v0.1.0", { root })).not.toThrow();
  });

  it("check-tag names every file that disagrees with the tag version", () => {
    const pkg = join(root, "package.json");
    writeFileSync(
      pkg,
      readFileSync(pkg, "utf8").replace('"version": "0.1.0"', '"version": "0.9.0"'),
    );
    const lockPath = join(root, "Cargo.lock");
    writeFileSync(
      lockPath,
      readFileSync(lockPath, "utf8").replace(
        'name = "oracle-core"\nversion = "0.1.0"',
        'name = "oracle-core"\nversion = "0.9.0"',
      ),
    );
    expect(() => runCheckTag("v0.1.0", { root })).toThrow(
      /version drift from v0\.1\.0: package\.json, Cargo\.lock \(oracle-core\)/,
    );
  });

  it("releases with a bot commit, an annotated tag, the release paths and the atomic push line", () => {
    const log = vi.spyOn(console, "log").mockImplementation(() => {});
    expect(release).not.toThrow();

    expect(git(root, ["log", "-1", "--format=%s|%an|%ae"]).trim()).toBe(
      "Release v0.1.1|devboule-bot|devboule-bot@devboule.invalid",
    );
    expect(git(root, ["cat-file", "-t", "v0.1.1"]).trim()).toBe("tag");
    expect(
      git(root, [
        "for-each-ref",
        "refs/tags/v0.1.1",
        "--format=%(taggername)|%(contents:subject)",
      ]).trim(),
    ).toBe("devboule-bot|Release v0.1.1");

    const committed = git(root, ["show", "--name-only", "--format=", "HEAD"])
      .split(/\r?\n/)
      .filter(Boolean)
      .sort();
    expect(committed).toEqual([...RELEASE_PATHS].sort());
    expect(log).toHaveBeenCalledWith("git push --atomic origin main v0.1.1");

    const changelog = readFileSync(join(root, "CHANGELOG.md"), "utf8");
    expect(changelog.indexOf("## [0.1.1]")).toBeGreaterThan(changelog.indexOf("## [Unreleased]"));
    // The [package]-scoped writer moved only the package version.
    const manifest = readFileSync(join(root, "src-tauri", "Cargo.toml"), "utf8");
    expect(manifest).toContain('version = "0.1.1"');
    expect(manifest).toContain('version = "1.0.0"');
    expect(git(root, ["status", "--porcelain=v1"])).toBe("");
  });
});
